/**
 * v3.44 비밀 직업(서버 전용, docs/concept.md 10장). 히든 직업 27개(v3.65 기준)와 그 계보를 완성된 모양 그대로 둡니다.
 * 이름·설명·조건(환생·숙련·교차 조건)·숙련 목표·힌트가 모두 여기 있고, 공개 표(classes.ts 등)에는 없습니다.
 * 서버가 register.ts로 직업 표에 더하고, 화면은 카탈로그로 드러난 것만(아니면 실루엣) 받습니다.
 * 화면 코드(components/·app/의 클라이언트)가 이 폴더를 가져가면 안 됩니다(scripts/check-secrets.mjs가 번들을 검사).
 * v3.61 subRole: 직업 역할(docs/concept.md 11.6-1, data/roles.ts).
 * 편집은 이 파일에서 합니다. 예전에 classes.ts 후처리(이름·칭호·숙련 목표 등)를 거친 결과를 v3.44에 그대로 옮겼습니다.
 */
// v3.49 서버 전용 표식: 화면(클라이언트) 번들이 이 파일을 가져가면 빌드가 실패합니다(docs/concept.md 10.2-1).
import 'server-only';
import type { Job, Lineage } from '../data/classes';

export const SECRET_JOBS: Job[] = [
    {id: 'voidcaller', subRole: 'magic', name: '아델 (2차)', title: '기록되지 않은 공허의 목소리', desc: '환생 이후에 드러나는 히든 직업. 마나 비례 주문과 높은 발동 확률.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.1, bonus: {magic: 42, hp: 20, resist: 7}, tier: 2, level: 25, parent: 'wanderer', requires: {int: 30, luk: 30}, mastery: 75, role: '히든·MP', tree: 'mystery', lineage: 'voidcaller', hidden: true, rebirth: 1, masteryTarget: 12000, masteryBoost: 0.28, hint: '윤회를 겪은 방랑자에게 공허가 속삭입니다.'},
    // v3.137 망인 숙달 목표 1,000만(제약형 패시브와 같은 천만 단위). 의미 없던 고정 페널티(마나 -10 · 마방 -3)를 지우고 물리 배율 .95 → .8.
    {id: 'undead', lineage: 'restraint', subRole: 'physical', name: '망인', title: '죽음과 함께 걷는 모험가', desc: '체력이 절반이고 물리·마법 공격과 두 방어도 크게 불리합니다. 죽지않은 영혼을 숙련하면 직업 페널티를 단계별로 되찾고, 3단계(숙련 1,000만)에서는 모두 되찾습니다.', attack: 0.8, magic: 0.75, hp: 0.5, defense: 0.8, resist: 0.7, crit: 0.02, tier: 1, level: 10, requires: {vit: 14, luk: 14}, mastery: 0, role: '페널티·숙련', tree: 'mystery', hidden: true, penalties: {accuracy: -0.08}, masteryTarget: 10000000, masteryBoost: 0.16, hint: '몇 번이고 쓰러져 본 모험가에게 죽음이 말을 겁니다.'},
    {id: 'manaLeviathan', subRole: 'magic', name: '아델 (3차)', title: '세계 전체를 주문으로 삼킨다', desc: 'MP 비례 주문을 극단까지 밀어붙이는 환생 후 3차 히든 직업입니다.', attack: 0.92, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.12, bonus: {magic: 102, resist: 12}, tier: 3, level: 40, parent: 'voidcaller', requires: {int: 50, wis: 38}, mastery: 150, role: 'MP·히든', tree: 'mystery', lineage: 'voidcaller', hidden: true, rebirth: 2, requiresSkillMastery: {voidLance: 4}, requiresJobMastery: {tide: 150}, masteryTarget: 270000, masteryBoost: 0.4, hint: '공허와 마나를 모두 익히고 윤회를 거듭한 자에게.'},
    {id: 'krakenkin', subRole: 'physical', name: '은월 (3차)', title: '보스의 기술을 의지로 묶는다', desc: '은월 (2차)의 계승을 마친 뒤 보스의 다중 공격을 사용할 수 있는 몬스터 계열 물리 3차 직업입니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.08, bonus: {attack: 70, hp: 90, defense: 1}, tier: 3, level: 40, parent: 'stormEel', requires: {str: 38, dex: 30}, mastery: 150, role: '몬스터·추가타', tree: 'physical', lineage: 'krakenkin', penalties: {accuracy: -0.04}, hidden: true, rebirth: 1, requiresSkillMastery: {electricBite: 4}, requiresJobMastery: {stormEel: 150}, masteryTarget: 300000, masteryBoost: 0.42, hint: '보스의 피를 숱하게 묻힌 모험가에게 혈족이 찾아옵니다.'},
    {id: 'voidSovereign', subRole: 'magic', name: '아델 (4차)', title: '비어 있음으로 채운다', desc: '공허 계보의 4차 히든 직업입니다. 칙령은 최대 마나를 쏟아부어 때리고, 패시브로 마나와 마법 공격을 올립니다.', attack: 1, magic: 1.52, hp: 1.18, defense: 1.12, resist: 1.21, crit: 0.12, tier: 4, level: 55, rebirth: 2, mastery: 300, masteryTarget: 300000, masteryBoost: 0.32, parent: 'manaLeviathan', requires: {int: 60, wis: 45}, requiresSkillMastery: {leviathanEquation: 3}, role: 'MP·최상위', tree: 'mystery', lineage: 'voidcaller', hidden: true, hint: '디바이드를 마치고 윤회를 거듭한 자에게.'},
    {id: 'deepHorror', subRole: 'physical', name: '은월 (4차)', title: '그림자가 빛을 삼킨다', desc: '몬스터 계보의 4차 히든 직업입니다. 난타로 여러 번 후려치고, 패시브로 체력과 방어를 받칩니다.', attack: 1.42, magic: 1, hp: 1.18, defense: 1.04, resist: 1, crit: 0.1, tier: 4, level: 55, rebirth: 1, mastery: 300, masteryTarget: 300000, masteryBoost: 0.32, parent: 'krakenkin', requires: {str: 52, dex: 38}, requiresSkillMastery: {tentacleBarrage: 3}, role: '몬스터·추가타', tree: 'physical', lineage: 'krakenkin', penalties: {accuracy: -0.04}, hidden: true, hint: '보스의 난타가 더 많은 적을 원할 때.'},
    {id: 'leviathanAvatar', subRole: 'physical', name: '은월 (5차)', title: '괴수가 몸을 얻었다', desc: '세계를 휘감는 난타로 몬스터 계열의 정점에 선 5차 히든 직업입니다.', attack: 1.56, magic: 1, hp: 1.25, defense: 1.08, resist: 1.06, crit: 0.12, tier: 5, level: 70, rebirth: 2, mastery: 300000, masteryTarget: 1500000, masteryBoost: 0.35, parent: 'deepHorror', requires: {str: 66, dex: 44, vit: 40}, requiresSkillMastery: {maulingTide: 3}, role: '몬스터 최상위', tree: 'physical', lineage: 'krakenkin', penalties: {accuracy: -0.04}, hidden: true, hint: '괴수의 난타가 세계 전체에 닿을 때.'},
    {id: 'voidIncarnate', subRole: 'magic', name: '아델 (5차)', title: '아무것도 없는 곳에서 모든 것이', desc: '최대 마나에 비례하는 인피니트와 거대한 마나·마법 공격 패시브로 아델 계보의 정점에 선 히든 5차 직업입니다.', attack: 1, magic: 1.75, hp: 1.18, defense: 1.08, resist: 1.3, crit: 0.12, tier: 5, level: 70, rebirth: 3, mastery: 300000, masteryTarget: 1500000, masteryBoost: 0.35, parent: 'voidSovereign', requires: {int: 74, wis: 56}, requiresSkillMastery: {abyssDecree: 3}, role: 'MP 최상위·히든', tree: 'mystery', lineage: 'voidcaller', hidden: true, hint: '거듭된 윤회 끝에 공허의 칙령이 완성될 때.'},
    {id: 'poorMonk', subRole: 'reflect', name: '청빈 수도승', title: '가진 것이 없어 잃을 것도 없다', desc: '호영 계보의 숨은 2차 직업. 흡혈하는 빈손 장타와, 골드를 내려놓는 대신 단단해지는 서약을 가집니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, bonus: {hp: 110, defense: 12, resist: 12}, tier: 2, level: 25, parent: 'saltWarden', requires: {vit: 24, wis: 24}, mastery: 75, role: '숨은 가지·청빈', tree: 'defense', hidden: true, masteryTarget: 3000, masteryBoost: 0.18, hint: '어느 정도 성장했는데도 주머니가 거의 비어 있을 때.'},
    {id: 'journeyman', subRole: 'utility', name: '떠돌이 모험가', title: '배운 것은 몸에 남는다', desc: '직업 셋을 끝까지 숙달한 자에게 열리는 패시브 전용 직업. 두 패시브가 숙달한 직업 수에 비례해 자라며, 계승하면 어느 직업에서든 그대로 힘이 됩니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 10, mastery: 0, tree: 'mystery', lineage: 'wander', hidden: true, masteryTarget: 4000, masteryBoost: 0.15, bonus: {attack: 2, magic: 2, hp: 10}, requires: {str: 10, int: 10, vit: 10}, role: '숙달·누적', fullKit: true, hint: '여러 직업을 끝까지 숙달한 모험가에게.'},
    {id: 'polymath', subRole: 'utility', name: '만능 모험가', title: '여덟 가지 삶을 한 몸에', desc: '직업 여덟을 숙달한 떠돌이 모험가에게 열리는 2차급 독립 직업. 숙달한 직업 수에 비례하는 복합 일격과 패시브를 가집니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.02, bonus: {attack: 4, magic: 4, hp: 20}, tier: 2, level: 25, mastery: 0, requires: {str: 20, int: 20, vit: 20}, requiresJobMastery: {journeyman: 4000}, requiresMastered: 8, role: '숙달·복합', tree: 'mystery', lineage: 'wander', hidden: true, fullKit: true, masteryTarget: 12000, masteryBoost: 0.2, hint: '떠돌이 모험가가 많은 삶을 숙달했을 때.'},
    {id: 'hundredLives', subRole: 'utility', name: '백수', title: '모든 생을 기억하는 모험가', desc: '직업 열다섯을 숙달한 자에게 열리는 3차급 독립 직업. 숙달한 직업 수만큼 강해지는 천 번의 삶과 패시브로 모든 숙련의 결산을 받습니다.', attack: 1, magic: 1, hp: 1.02, defense: 1, resist: 1, crit: 0.03, bonus: {attack: 12, magic: 12, hp: 60, defense: 3, resist: 3}, tier: 3, level: 40, mastery: 0, requires: {str: 30, int: 30, vit: 30}, requiresJobMastery: {polymath: 12000}, requiresMastered: 15, role: '숙달·결산', tree: 'mystery', lineage: 'wander', hidden: true, fullKit: true, masteryTarget: 120000, masteryBoost: 0.3, hint: '만능 모험가가 그보다 더 많은 삶을 숙달했을 때.'},
    {id: 'clockmaker', subRole: 'border', name: '제로 (1차)', title: '고장 난 시간을 고친다', desc: '자신을 가속하고 상대를 감속하는 시간 직업. 가끔 타임 리와인드가 작동해 나와 상대가 모두 처음 상태로 돌아갑니다. 끝까지 숙달하면 제로 (4차)가 열립니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, bonus: {attack: 2, magic: 2, hp: 5}, tier: 1, level: 10, mastery: 0, requires: {dex: 12, int: 10}, role: '시간·속도', tree: 'mystery', lineage: 'zero', hidden: true, fullKit: true, masteryTarget: 3000, masteryBoost: 0.2, hint: '사냥터에서 오랜 시간을 보낸 뒤, 시계 소리가 들립니다.'},
    {id: 'chronarch', subRole: 'border', name: '제로 (4차)', title: '멈춘 시간 속을 홀로 걷는다', desc: '제로 (1차)를 숙달한 자에게만 열리는 4차급 독립 직업. 확정 기절과 확정 추가 행동으로 전투의 시간을 지배합니다.', attack: 1.3, magic: 1.3, hp: 1.12, defense: 1.08, resist: 1.08, crit: 0.08, tier: 4, level: 10, mastery: 0, requires: {}, requiresJobMastery: {clockmaker: 3000}, role: '시간·제어', tree: 'mystery', lineage: 'zero', hidden: true, fullKit: true, masteryTarget: 450000, masteryBoost: 0.35, hint: '시계의 모든 톱니를 맞춘 자에게.'},
    {id: 'hacker', subRole: 'none', name: '해커', title: '게임의 헛점을 파고든다', desc: '전투 능력은 전무합니다. 사냥·던전·결투·월드보스·신 도전에 참여할 수 없고, 능력치 투자와 해커 전용이 아닌 스킬 장착이 막히며, 해커로 있는 동안 레벨·경험치가 멈춥니다. 대신 침투 작전으로 비트와 권한을 쌓고, 서버의 방송을 탈취하고 다른 모험가의 숨김을 깨뜨립니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 30, rebirth: 3, mastery: 0, requires: {}, role: '해킹·서버', tree: 'mystery', lineage: 'hacker', hidden: true, hint: '윤회를 거듭한 자에게 서버의 틈이 보입니다.', masteryTarget: 3000, masteryBoost: 0},
    {id: 'blackHacker', subRole: 'none', name: '블랙 해커', title: '흔적을 남기지 않는 자', desc: '해커와 같은 제약(전투 불가, 레벨·경험치 정지)을 받습니다. 해킹의 하루 횟수가 두 배(쿨다운 절반)지만 비트도 두 배로 들고, 해킹마다 실패 확률(35% − 단계×3%, 최소 5%)이 있습니다. 실패하면 비트·횟수만 쓰이고, 추적되어 소식에 이름이 공지되며 6시간 동안 해킹할 수 없습니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 2, level: 30, rebirth: 3, parent: 'hacker', mastery: 1500, requires: {}, role: '고위험 해킹', tree: 'mystery', lineage: 'hacker', hidden: true, hint: '해커로 서버를 충분히 들여다본 자에게 더 어두운 길이 보입니다.', masteryTarget: 6000, masteryBoost: 0},
    {id: 'whiteHacker', subRole: 'none', name: '화이트 해커', title: '뚫린 곳을 막는 자', desc: '해커와 같은 제약(전투 불가, 레벨·경험치 정지)을 받습니다. 공격 해킹(방송 탈취·크래킹·이벤트 변조·서버 다운) 대신 다른 해커의 해킹을 되돌리고(현상금으로 비트), 사냥터·던전을 패치해 한 시간 동안 서버 다운을 막습니다. 전용 패시브 방화벽은 하루 한 번 크래킹을 막아 냅니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 2, level: 30, rebirth: 3, parent: 'hacker', mastery: 1500, requires: {}, role: '복구·패치', tree: 'mystery', lineage: 'hacker', hidden: true, hint: '해커로 서버를 충분히 들여다본 자에게 반대편 길이 보입니다.', masteryTarget: 6000, masteryBoost: 0},
];
export const SECRET_LINEAGES: Lineage[] = [
    // v3.135 나이트워커 계보 폐지: 2~5차 · 골령술사를 지우고 1차 망인(undead)만 제약 계보(data/specials.ts)로 돌려보냅니다.
    {id: 'voidcaller', name: '아델 계보', tree: 'mystery', summary: '환생 이후에 드러나는 마나 연소 히든 계보입니다. 고정 마나 소모 없이 현재 마나의 일부를 태워 그만큼 피해에 더하고, 큰 마나 통과 마나 회복이 연료가 됩니다.'},
    /** v3.65 숙달 사다리(떠돌이 → 만능 → 백수)를 ‘방랑’ 계보로, 제로를 자기 계보로 묶습니다. 은월은 공개 계보(classes.ts)로 옮겼습니다. */
    {id: 'wander', name: '방랑 계보', tree: 'mystery', summary: '여러 직업을 끝까지 숙달할수록 강해지는 숨은 계보입니다.'},
    {id: 'zero', name: '제로 계보', tree: 'mystery', summary: '역할의 경계에 선 숨은 계보입니다. 시간을 되감아 판을 다시 짭니다.'},
    {id: 'hacker', name: '해커 계보', tree: 'mystery', summary: '전투 대신 침투 작전과 해킹으로 자라는 계보입니다. 화이트 해커는 해킹을 되돌리고 서버를 지키고, 블랙 해커는 더 자주·더 비싸게 해킹하다 추적당할 위험을 집니다.'},
];
