/**
 * v3.44 비밀 직업(서버 전용, docs/concept.md 10장). 히든 직업과 ??? 문 직업 35개와 그 계보 4개를 완성된 모양 그대로 둡니다.
 * 이름·설명·조건(환생·숙련·교차 조건)·숙련 목표·힌트가 모두 여기 있고, 공개 표(classes.ts 등)에는 없습니다.
 * 서버가 register.ts로 직업 표에 더하고, 화면은 카탈로그로 드러난 것만(아니면 실루엣) 받습니다.
 * 화면 코드(components/·app/의 클라이언트)가 이 폴더를 가져가면 안 됩니다(scripts/check-secrets.mjs가 번들을 검사).
 * 편집은 이 파일에서 합니다. 예전에 classes.ts 후처리(이름·칭호·숙련 목표 등)를 거친 결과를 v3.44에 그대로 옮겼습니다.
 */
// v3.49 서버 전용 표식: 화면(클라이언트) 번들이 이 파일을 가져가면 빌드가 실패합니다(docs/concept.md 10.2-1).
import 'server-only';
import type { Job, Lineage } from '../data/classes';

export const SECRET_JOBS: Job[] = [
    {id: 'voidcaller', name: '아델 (2차)', title: '기록되지 않은 공허의 목소리', desc: '환생 이후에 드러나는 히든 직업. 마나 비례 주문과 높은 발동 확률.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.1, bonus: {magic: 42, hp: 20, resist: 7}, tier: 2, level: 25, parent: 'wanderer', requires: {int: 30, luk: 30}, mastery: 75, role: '히든·MP', tree: 'mystery', lineage: 'voidcaller', hidden: true, rebirth: 1, masteryTarget: 12000, masteryBoost: 0.28, hint: '한 번의 윤회를 넘긴 제논 (1차)에게 윤회의 문이 속삭입니다.'},
    {id: 'undead', name: '나이트워커 (1차)', title: '죽음과 함께 걷는 모험가', desc: '체력이 절반이고 마법·방어도 크게 불리합니다. 쉐도우 서번트를 숙련하면 직업 페널티를 단계별로 되찾고, 3단계에서는 모두 되찾습니다.', attack: 0.95, magic: 0.75, hp: 0.5, defense: 0.8, resist: 0.7, crit: 0.02, tier: 1, level: 10, requires: {vit: 14, luk: 14}, mastery: 0, role: '페널티·숙련', tree: 'mystery', hidden: true, penalties: {accuracy: -0.08, mana: -10, resist: -3}, masteryTarget: 2400, masteryBoost: 0.16, hint: '열 번 쓰러져 본 모험가에게 죽음이 말을 겁니다.'},
    {id: 'glassHarpooner', name: '유리 대포', title: '한 번 맞으면 깨지는 몸', desc: '최대 체력이 1%뿐인 제약 직업입니다. 항상 먼저 움직이고, 쓰러질 피해를 전투당 두 번 체력 1로 버티며, 회피 +30%p로 피합니다. 물리 공격 ×2.2·치명타 +15%로 맞기 전에 끝내는 결투·계승용 직업입니다.', attack: 2.2, magic: 1, hp: 0.01, defense: 1, resist: 1, crit: 0.15, tier: 1, level: 10, requires: {dex: 14, luk: 14}, mastery: 0, role: '제약·유리 대포', tree: 'mystery', hidden: true, branchless: true, hint: '한 대도 맞을 수 없는 몸으로 먼저 찌르는 모험가.', constraint: {label: '유리 몸', desc: '최대 체력 1%. 선공·최후의 버팀·회피로만 살아남습니다.', devices: {firstStrike: true, lastStand: {charges: 2}, evasion: 0.3}}, masteryTarget: 300, masteryBoost: 0.08},
    {id: 'skeleton', name: '나이트워커 (2차)', title: '부서져도 다시 선다', desc: '최대 체력은 낮지만 방어와 골격의 힘으로 버티는 페널티 극복형 직업.', attack: 1, magic: 0.6, hp: 0.5, defense: 1, resist: 0.6, crit: 0.04, bonus: {attack: 19, defense: 8}, tier: 2, level: 25, parent: 'undead', requires: {str: 32, vit: 24}, mastery: 75, role: '골격·방어', tree: 'mystery', hidden: true, penalties: {accuracy: -0.1, mana: -14, resist: -5}, masteryTarget: 9000, masteryBoost: 0.26, hint: '망인의 뼈가 단단해질 때 드러납니다.'},
    {id: 'bonecaster', name: '골령술사', title: '마나로 뼈를 세우는 자', desc: '약한 육체와 낮은 명중을 감수하고 마나·마법 방어·숙련 보상에 투자하는 히든 직업.', attack: 0.6, magic: 1, hp: 0.5, defense: 0.6, resist: 1, crit: 0.06, bonus: {magic: 33, resist: 5}, tier: 2, level: 25, parent: 'undead', requires: {int: 32, wis: 24}, mastery: 75, role: '골령·마법', tree: 'mystery', hidden: true, penalties: {accuracy: -0.12, mana: -6, defense: -3}, masteryTarget: 10000, masteryBoost: 0.28, hint: '망인의 뼈에 마나를 새길 때 드러납니다.'},
    {id: 'manaLeviathan', name: '아델 (3차)', title: '세계 전체를 주문으로 삼킨다', desc: 'MP 비례 주문을 극단까지 밀어붙이는 환생 후 3차 히든 직업입니다.', attack: 0.92, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.12, bonus: {magic: 102, resist: 12}, tier: 3, level: 40, parent: 'voidcaller', requires: {int: 50, wis: 38}, mastery: 150, role: 'MP·히든', tree: 'mystery', lineage: 'voidcaller', hidden: true, rebirth: 2, requiresSkillMastery: {voidLance: 4}, requiresJobMastery: {tide: 150}, masteryTarget: 270000, masteryBoost: 0.4, hint: '공허와 마나를 모두 익히고 두 번의 윤회를 건넌 자에게.'},
    {id: 'soulHarvester', name: '나이트워커 (3차)', title: '쓰러진 적의 그림자를 거둔다', desc: '망인 계열의 페널티를 치명타와 흡혈로 뒤집는 히든 3차 직업입니다.', attack: 1, magic: 0.7, hp: 0.7, defense: 1, resist: 0.7, crit: 0.18, bonus: {attack: 59, defense: 7}, tier: 3, level: 40, parent: 'skeleton', requires: {str: 44, luk: 38}, mastery: 150, role: '치명·영혼', tree: 'mystery', hidden: true, requiresSkillMastery: {marrowGuard: 4, boneLegacy: 3}, requiresJobMastery: {undead: 150}, masteryTarget: 210000, masteryBoost: 0.4, hint: '나이트워커 (2차)와 망인의 기억이 깊이 쌓일 때.'},
    {id: 'krakenkin', name: '은월 (3차)', title: '보스의 기술을 의지로 묶는다', desc: '은월 (2차)의 계승을 마친 뒤 보스의 다중 공격을 사용할 수 있는 몬스터 계열 물리 3차 직업입니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.08, bonus: {attack: 70, hp: 90, defense: 1}, tier: 3, level: 40, parent: 'stormEel', requires: {str: 38, dex: 30}, mastery: 150, role: '몬스터·추가타', tree: 'mystery', lineage: 'krakenkin', penalties: {accuracy: -0.04}, hidden: true, rebirth: 1, requiresSkillMastery: {electricBite: 4}, requiresJobMastery: {stormEel: 150}, masteryTarget: 300000, masteryBoost: 0.42, hint: '보스 열 마리의 피를 묻힌 모험가에게 혈족이 찾아옵니다.'},
    {id: 'eternalNavigator', name: '시공의 위자드', title: '세 번째 삶에 만난 시간', desc: '환생으로 시공의 파동에 도달하는 상위 직업. 상대를 쓰러뜨리면 대기 중인 모든 기술이 돌아와, 연속 처치가 끊기지 않는 방치형 분기입니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.04, bonus: {magic: 92, resist: 6}, tier: 3, level: 40, rebirth: 3, parent: 'tempest', requires: {int: 45, wis: 40}, mastery: 3000, requiresSkillMastery: {maelstrom: 3}, role: '환생·상위 주문', tree: 'magic', hidden: true, masteryTarget: 180000, masteryBoost: 0.36, hint: '세 번의 윤회와 폭풍을 모두 건넌 술사에게.'},
    {id: 'rebirthFisher', name: '윤회의 나그네', title: '다시 내딛는 첫걸음', desc: '윤회의 일격을 배우는 환생 전용 독립 직업. 회복을 동반하는 공격기를 다음 삶의 편성에 남깁니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, bonus: {attack: 1, hp: 5}, tier: 1, level: 10, rebirth: 1, requires: {str: 10, wis: 12}, mastery: 0, role: '독립·환생 흡혈', tree: 'mystery', branchless: true, masteryTarget: 6000, masteryBoost: 0.15, hint: '환생 뒤, 윤회의 문이 이 이름을 부를 때.'},
    {id: 'lichKing', name: '나이트워커 (4차)', title: '죽음의 왕좌에 앉은 모험가', desc: '망인 계보의 환생 후 4차 히든 직업입니다. 쉐도우 스피어로 때린 만큼 흡혈하고, 패시브로 체력과 치명타를 올립니다.', attack: 1.39, magic: 1.07, hp: 1.04, defense: 1.14, resist: 1, crit: 0.2, tier: 4, level: 55, rebirth: 1, mastery: 300, masteryTarget: 300000, masteryBoost: 0.32, parent: 'soulHarvester', requires: {str: 54, luk: 42}, requiresSkillMastery: {harvestEcho: 3}, role: '치명·영혼 군주', tree: 'mystery', hidden: true, hint: '영혼을 충분히 거둔 수확자가 두 번째 삶에서 왕좌를 봅니다.'},
    {id: 'voidDrifter', name: '허공 방랑자', title: '어디에도 닿지 않는 걸음', desc: '마나 비례 주문과 회피·마나 패시브로 싸우는 공허 계열 3차 히든 직업입니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.12, bonus: {magic: 83, resist: 6}, tier: 3, level: 40, mastery: 150, rebirth: 1, parent: 'voidcaller', requires: {int: 46, luk: 40}, requiresSkillMastery: {voidLance: 3}, role: 'MP·회피', tree: 'mystery', lineage: 'voidcaller', hidden: true, masteryTarget: 36000, masteryBoost: 0.3, hint: '샤드를 깊이 익힌 기록자가 걸음을 옮길 때.'},
    {id: 'voidSovereign', name: '아델 (4차)', title: '비어 있음으로 채운다', desc: '공허 계보의 4차 히든 직업입니다. 칙령은 최대 마나를 쏟아부어 때리고, 패시브로 마나와 마법 공격을 올립니다.', attack: 1, magic: 1.52, hp: 1.18, defense: 1.12, resist: 1.21, crit: 0.12, tier: 4, level: 55, rebirth: 2, mastery: 300, masteryTarget: 300000, masteryBoost: 0.32, parent: 'manaLeviathan', requires: {int: 60, wis: 45}, requiresSkillMastery: {leviathanEquation: 3}, role: 'MP·최상위', tree: 'mystery', lineage: 'voidcaller', hidden: true, hint: '디바이드를 마치고 두 번의 윤회를 건넌 자에게.'},
    {id: 'deepHorror', name: '은월 (4차)', title: '그림자가 빛을 삼킨다', desc: '몬스터 계보의 4차 히든 직업입니다. 난타로 여러 번 후려치고, 패시브로 체력과 방어를 받칩니다.', attack: 1.42, magic: 1, hp: 1.18, defense: 1.04, resist: 1, crit: 0.1, tier: 4, level: 55, rebirth: 1, mastery: 300, masteryTarget: 300000, masteryBoost: 0.32, parent: 'krakenkin', requires: {str: 52, dex: 38}, requiresSkillMastery: {tentacleBarrage: 3}, role: '몬스터·추가타', tree: 'mystery', lineage: 'krakenkin', penalties: {accuracy: -0.04}, hidden: true, hint: '보스의 난타가 더 많은 적을 원할 때.'},
    {id: 'tideDevourer', name: '구미호', title: '모든 것을 삼키는 입', desc: '몬스터 계보의 4차 히든 직업입니다. 포식은 삼킨 만큼 회복하고, 패시브로 체력과 흡혈을 올립니다.', attack: 1.36, magic: 1, hp: 1.21, defense: 1, resist: 1, crit: 0.08, tier: 4, level: 55, rebirth: 1, mastery: 300, masteryTarget: 300000, masteryBoost: 0.32, parent: 'krakenkin', requires: {str: 50, vit: 40}, requiresSkillMastery: {tentacleBarrage: 3}, role: '몬스터·흡혈', tree: 'mystery', lineage: 'krakenkin', hidden: true, hint: '보스의 굶주림이 끝나지 않을 때.'},
    {id: 'leviathanAvatar', name: '은월 (5차)', title: '괴수가 몸을 얻었다', desc: '세계를 휘감는 난타로 몬스터 계열의 정점에 선 5차 히든 직업입니다.', attack: 1.56, magic: 1, hp: 1.25, defense: 1.08, resist: 1.06, crit: 0.12, tier: 5, level: 70, rebirth: 2, mastery: 300000, masteryTarget: 1500000, masteryBoost: 0.35, parent: 'deepHorror', requires: {str: 66, dex: 44, vit: 40}, requiresSkillMastery: {maulingTide: 3}, role: '몬스터 최상위', tree: 'mystery', lineage: 'krakenkin', penalties: {accuracy: -0.04}, hidden: true, hint: '괴수의 난타가 세계 전체에 닿을 때.'},
    {id: 'deathEmperor', name: '나이트워커 (5차)', title: '죽음조차 거느리는 황제', desc: '영혼을 거두며 흡혈하는 쉐도우 바이트와 치명·흡혈·공격 패시브로 망인 계보의 정점에 선 히든 5차 직업입니다.', attack: 1.55, magic: 1.1, hp: 1.12, defense: 1.15, resist: 1, crit: 0.2, tier: 5, level: 70, rebirth: 2, mastery: 300000, masteryTarget: 1500000, masteryBoost: 0.35, parent: 'lichKing', requires: {str: 68, luk: 54}, requiresSkillMastery: {soulTyranny: 3}, role: '치명·영혼 최상위', tree: 'mystery', lineage: 'undead', hidden: true, hint: '나이트워커 (4차)가 영혼의 폭정을 완성한 날.'},
    {id: 'voidIncarnate', name: '아델 (5차)', title: '아무것도 없는 곳에서 모든 것이', desc: '최대 마나에 비례하는 인피니트와 거대한 마나·마법 공격 패시브로 아델 계보의 정점에 선 히든 5차 직업입니다.', attack: 1, magic: 1.75, hp: 1.18, defense: 1.08, resist: 1.3, crit: 0.12, tier: 5, level: 70, rebirth: 3, mastery: 300000, masteryTarget: 1500000, masteryBoost: 0.35, parent: 'voidSovereign', requires: {int: 74, wis: 56}, requiresSkillMastery: {abyssDecree: 3}, role: 'MP 최상위·히든', tree: 'mystery', lineage: 'voidcaller', hidden: true, hint: '세 번의 윤회 끝에 공허의 칙령이 완성될 때.'},
    {id: 'headwindSailor', name: '역풍의 모험가', title: '거꾸로 부는 바람을 탄다', desc: '다섯 번째 사냥터에 닿은 자에게 열리는 모험가. 스스로 가속하는 태킹과 속도·회피 패시브를 가집니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 10, mastery: 0, tree: 'mystery', branchless: true, hidden: true, masteryTarget: 2000, masteryBoost: 0.12, bonus: {attack: 2, hp: 5}, requires: {dex: 12, luk: 10}, role: '시간·속도', penalties: {defense: -2}, hint: '다섯 번째 사냥터까지 거슬러 올라간 모험가에게.'},
    {id: 'sunriseAngler', name: '해돋이 모험가', title: '첫 햇살에 줄을 던진다', desc: '열다섯 종을 만난 자에게 열리는 술사. 여명 섬광과 마나 회복 패시브로 주문을 자주 씁니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 10, mastery: 0, tree: 'mystery', branchless: true, hidden: true, masteryTarget: 2000, masteryBoost: 0.12, bonus: {magic: 5}, requires: {int: 12, wis: 10}, role: '시간·마나', penalties: {attack: -2}, hint: '열다섯 종의 몬스터를 처음 만난 아침에.'},
    {id: 'barehandFisher', name: '맨손 격투가', title: '무기도 필요 없다', desc: '무기 없이 버틴 자에게 열리는 격투가. 방어를 버리고 맨손으로 큰 한 방을 노립니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 10, mastery: 0, tree: 'mystery', branchless: true, hidden: true, masteryTarget: 2000, masteryBoost: 0.12, bonus: {attack: 4}, requires: {str: 14}, role: '시간·공격', penalties: {defense: -3, mana: -4}, hint: '무기 없이 열다섯 레벨을 넘긴 모험가에게.'},
    {id: 'noonDiver', name: '한낮의 수련생', title: '뜨거운 해 아래 가장 깊이', desc: '던전을 다섯 번 정복한 자에게 열리는 잠수부. 최대 체력에 비례하는 잠수 공격과 체력·방어 패시브를 가집니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 10, mastery: 0, tree: 'mystery', branchless: true, hidden: true, masteryTarget: 2000, masteryBoost: 0.12, bonus: {hp: 15, defense: 1}, requires: {vit: 14}, role: '시간·체력', penalties: {speed: -2}, hint: '던전 다섯 번을 끝까지 잠수한 자에게.'},
    {id: 'mistSwordsman', name: '안개 검객', title: '보이지 않는 칼끝', desc: '결투에서 이겨 본 자에게 열리는 검객. 명중이 높은 안개 베기와 회피·치명 패시브를 가집니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.02, tier: 1, level: 10, mastery: 0, tree: 'mystery', branchless: true, hidden: true, masteryTarget: 2000, masteryBoost: 0.12, bonus: {attack: 3}, requires: {dex: 12, str: 10}, role: '시간·회피', penalties: {hp: -10}, hint: '결투에서 세 번 이긴 뒤 안개가 걷힙니다.'},
    {id: 'nightHeron', name: '밤왜가리 사냥꾼', title: '움직이지 않고 기다린다', desc: '오백 마리를 낚은 자에게 열리는 사냥꾼. 피해 없이 감속을 거는 정적과 명중·치명 패시브를 가집니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 10, mastery: 0, tree: 'mystery', branchless: true, hidden: true, masteryTarget: 2000, masteryBoost: 0.12, bonus: {attack: 2, magic: 1}, requires: {dex: 10, luk: 12}, role: '시간·감속', penalties: {resist: -2}, hint: '오백 마리를 낚고도 물가를 떠나지 않은 자에게.'},
    {id: 'poorMonk', name: '청빈 수도승', title: '가진 것이 없어 잃을 것도 없다', desc: '빈손으로 싸우는 수도승. 흡혈하는 빈손 장타와 골드를 내려놓는 대신 단단해지는 서약을 가집니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 10, mastery: 0, tree: 'mystery', branchless: true, hidden: true, masteryTarget: 2000, masteryBoost: 0.12, bonus: {hp: 10, resist: 1}, requires: {vit: 12, wis: 12}, role: '발견·생존', penalties: {crit: -0.01}, hint: '어느 정도 성장했는데도 주머니가 거의 비어 있을 때.'},
    {id: 'codexReader', name: '몬스터 도감 독자', title: '모든 몬스터를 읽었다', desc: '도감을 깊이 읽은 자에게 열리는 술사. 도감 기록에 비례하는 주문과 패시브를 가집니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 10, mastery: 0, tree: 'mystery', branchless: true, hidden: true, masteryTarget: 2000, masteryBoost: 0.12, bonus: {magic: 5, resist: 1}, requires: {int: 14}, role: '발견·도감', penalties: {hp: -10}, hint: '도감에 기록이 서른 개 넘게 쌓였을 때.'},
    {id: 'journeyman', name: '떠돌이 모험가', title: '배운 것은 몸에 남는다', desc: '직업 셋을 끝까지 숙달한 자에게 열리는 패시브 전용 직업. 두 패시브가 숙달한 직업 수에 비례해 자라며, 계승하면 어느 직업에서든 그대로 힘이 됩니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 10, mastery: 0, tree: 'mystery', branchless: true, hidden: true, masteryTarget: 4000, masteryBoost: 0.15, bonus: {attack: 2, magic: 2, hp: 10}, requires: {str: 10, int: 10, vit: 10}, role: '숙달·누적', fullKit: true, hint: '직업 셋을 끝까지 숙달한 모험가에게.'},
    {id: 'polymath', name: '만능 모험가', title: '여덟 가지 삶을 한 몸에', desc: '직업 여덟을 숙달한 떠돌이 모험가에게 열리는 2차급 독립 직업. 숙달한 직업 수에 비례하는 복합 일격과 패시브를 가집니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.02, bonus: {attack: 4, magic: 4, hp: 20}, tier: 2, level: 25, mastery: 0, requires: {str: 20, int: 20, vit: 20}, requiresJobMastery: {journeyman: 4000}, requiresMastered: 8, role: '숙달·복합', tree: 'mystery', lineage: 'mystery-independent', branchless: true, hidden: true, fullKit: true, masteryTarget: 12000, masteryBoost: 0.2, hint: '떠돌이 모험가가 여덟 가지 삶을 모두 숙달했을 때.'},
    {id: 'hundredLives', name: '백수', title: '모든 생을 기억하는 모험가', desc: '직업 열다섯을 숙달한 자에게 열리는 3차급 독립 직업. 숙달한 직업 수만큼 강해지는 천 번의 삶과 패시브로 모든 숙련의 결산을 받습니다.', attack: 1, magic: 1, hp: 1.02, defense: 1, resist: 1, crit: 0.03, bonus: {attack: 12, magic: 12, hp: 60, defense: 3, resist: 3}, tier: 3, level: 40, mastery: 0, requires: {str: 30, int: 30, vit: 30}, requiresJobMastery: {polymath: 12000}, requiresMastered: 15, role: '숙달·결산', tree: 'mystery', lineage: 'mystery-independent', branchless: true, hidden: true, fullKit: true, masteryTarget: 120000, masteryBoost: 0.3, hint: '만능 모험가가 열다섯 가지 삶을 모두 숙달했을 때.'},
    {id: 'fallenAngler', name: '칠전팔기 모험가', title: '넘어진 만큼 일어선다', desc: '여러 번 쓰러져 본 자에게 열리는 직업. 흡혈하는 일어서기와 체력·흡혈 패시브를 가집니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 10, mastery: 0, tree: 'mystery', branchless: true, hidden: true, masteryTarget: 2000, masteryBoost: 0.12, bonus: {hp: 15, attack: 1}, requires: {vit: 12, str: 10}, role: '발견·흡혈', penalties: {speed: -2}, hint: '서른 번쯤 쓰러져 본 모험가에게.'},
    {id: 'clockmaker', name: '제로 (1차)', title: '고장 난 시간을 고친다', desc: '자신을 가속하고 상대를 감속하는 시간 직업. 가끔 타임 리와인드가 작동해 나와 상대가 모두 처음 상태로 돌아갑니다. 끝까지 숙달하면 제로 (4차)가 열립니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, bonus: {attack: 2, magic: 2, hp: 5}, tier: 1, level: 10, mastery: 0, requires: {dex: 12, int: 10}, role: '시간·속도', tree: 'mystery', branchless: true, hidden: true, fullKit: true, masteryTarget: 3000, masteryBoost: 0.2, hint: '사냥터에서 열 시간을 보낸 뒤, 시계 소리가 들립니다.'},
    {id: 'chronarch', name: '제로 (4차)', title: '멈춘 시간 속을 홀로 걷는다', desc: '제로 (1차)를 숙달한 자에게만 열리는 4차급 독립 직업. 확정 기절과 확정 추가 행동으로 전투의 시간을 지배합니다.', attack: 1.3, magic: 1.3, hp: 1.12, defense: 1.08, resist: 1.08, crit: 0.08, tier: 4, level: 10, mastery: 0, requires: {}, requiresJobMastery: {clockmaker: 3000}, role: '시간·제어', tree: 'mystery', lineage: 'mystery-independent', hidden: true, fullKit: true, masteryTarget: 450000, masteryBoost: 0.35, hint: '제로 (1차)의 모든 톱니를 맞춘 자에게.'},
    {id: 'hacker', name: '해커', title: '게임의 헛점을 파고든다', desc: '전투 능력은 전무합니다. 사냥·던전·결투·월드보스·신 도전에 참여할 수 없고, 능력치 투자와 해커 전용이 아닌 스킬 장착이 막히며, 해커로 있는 동안 레벨·경험치가 멈춥니다. 대신 침투 작전으로 비트와 권한을 쌓고, 서버의 방송을 탈취하고 다른 모험가의 숨김을 깨뜨립니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 30, rebirth: 3, mastery: 0, requires: {}, role: '해킹·서버', tree: 'mystery', lineage: 'hacker', hidden: true, hint: '세 번의 윤회를 넘긴 자에게 서버의 틈이 보입니다.', masteryTarget: 3000, masteryBoost: 0},
    {id: 'blackHacker', name: '블랙 해커', title: '흔적을 남기지 않는 자', desc: '해커와 같은 제약(전투 불가, 레벨·경험치 정지)을 받습니다. 해킹의 하루 횟수가 두 배(쿨다운 절반)지만 비트도 두 배로 들고, 해킹마다 실패 확률(35% − 단계×3%, 최소 5%)이 있습니다. 실패하면 비트·횟수만 쓰이고, 추적되어 소식에 이름이 공지되며 6시간 동안 해킹할 수 없습니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 2, level: 30, rebirth: 3, parent: 'hacker', mastery: 1500, requires: {}, role: '고위험 해킹', tree: 'mystery', lineage: 'hacker', hidden: true, hint: '해커로 서버를 충분히 들여다본 자에게 더 어두운 길이 보입니다.', masteryTarget: 6000, masteryBoost: 0},
    {id: 'whiteHacker', name: '화이트 해커', title: '뚫린 곳을 막는 자', desc: '해커와 같은 제약(전투 불가, 레벨·경험치 정지)을 받습니다. 공격 해킹(방송 탈취·크래킹·이벤트 변조·서버 다운) 대신 다른 해커의 해킹을 되돌리고(현상금으로 비트), 사냥터·던전을 패치해 한 시간 동안 서버 다운을 막습니다. 전용 패시브 방화벽은 하루 한 번 크래킹을 막아 냅니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 2, level: 30, rebirth: 3, parent: 'hacker', mastery: 1500, requires: {}, role: '복구·패치', tree: 'mystery', lineage: 'hacker', hidden: true, hint: '해커로 서버를 충분히 들여다본 자에게 반대편 길이 보입니다.', masteryTarget: 6000, masteryBoost: 0},
];
export const SECRET_LINEAGES: Lineage[] = [
    {id: 'undead', name: '나이트워커 계보', tree: 'mystery', summary: '불리한 몸을 숙련으로 극복하는 골격·골령 계보입니다.'},
    {id: 'voidcaller', name: '아델 계보', tree: 'mystery', summary: '환생 이후에 드러나는 마나 비례 히든 계보입니다.'},
    {id: 'krakenkin', name: '은월 계보', tree: 'mystery', summary: '몬스터의 피를 이은 추가타 직업입니다.'},
    {id: 'hacker', name: '해커 계보', tree: 'mystery', summary: '전투 대신 침투 작전과 해킹으로 자라는 계보입니다. 화이트 해커는 해킹을 되돌리고 서버를 지키고, 블랙 해커는 더 자주·더 비싸게 해킹하다 추적당할 위험을 집니다.'},
];
