/**
 * v3.44 비밀 직업(서버 전용, docs/concept.md 10장). 히든 직업 27개(v3.65 기준)와 그 계보를 완성된 모양 그대로 둡니다.
 * 이름·설명·조건(환생·숙련·교차 조건)·숙련 목표·힌트가 모두 여기 있고, 공개 표(classes.ts 등)에는 없습니다.
 * 서버가 register.ts로 직업 표에 더하고, 화면은 카탈로그로 드러난 것만(아니면 실루엣) 받습니다.
 * 화면 코드(components/·app/의 클라이언트)가 이 폴더를 가져가면 안 됩니다(scripts/check-secrets.mjs가 번들을 검사).
 * v3.61 subRole: 직업 역할(docs/concept.md 11.6-1, data/roles.ts).
 * v3.199 히든 정리: 은월 3~5차는 공개 전직(data/specials.ts)으로, 청빈 수도승은 삭제, 제로 (4차) → 제로 (5차). 히든 조건을 모두 올렸습니다(아델 환생 2 · 3 · 4 · 5, 방랑 숙달 5 · 12 · 20, 해커 환생 5).
 * v3.198 히든 리메이크: 계보마다 공개 직업에 없는 규칙 하나(제로 태그 · 방랑 AP 할인 · 청빈 빈 자릿수 · 망인 흡혈 · 아델 마나 연소 · 은월 정령)로 정체성을 다시 세웠습니다(docs/concept.md 11.10).
 * 편집은 이 파일에서 합니다. 예전에 classes.ts 후처리(이름·칭호·숙련 목표 등)를 거친 결과를 v3.44에 그대로 옮겼습니다.
 */
// v3.49 서버 전용 표식: 화면(클라이언트) 번들이 이 파일을 가져가면 빌드가 실패합니다(docs/concept.md 10.2-1).
import 'server-only';
import type { Job, Lineage } from '../data/classes';

export const SECRET_JOBS: Job[] = [
    {id: 'voidcaller', subRole: 'magic', name: '아델 (2차)', title: '기록되지 않은 공허의 목소리', desc: '환생 이후에 드러나는 히든 직업. 마나 비례 주문과 높은 발동 확률.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.1, bonus: {magic: 42, hp: 20, resist: 7}, tier: 2, level: 25, parent: 'wanderer', requires: {int: 30, luk: 30}, mastery: 75, role: '히든·MP', tree: 'mystery', lineage: 'voidcaller', hidden: true, rebirth: 2, masteryTarget: 12000, masteryBoost: 0.28, hint: '윤회를 겪은 방랑자에게 공허가 속삭입니다.'},
    // v3.137 망인 숙달 목표 1,000만(제약형 패시브와 같은 천만 단위).
    {id: 'undead', lineage: 'restraint', subRole: 'physical', name: '망인', title: '죽음과 함께 걷는 모험가', desc: '체력이 절반이고 물리·마법 공격과 두 방어도 크게 불리합니다. 죽지않은 영혼을 숙련하면 직업 페널티를 단계별로 되찾고, 3단계(숙련 1,000만)에서는 모두 되찾습니다.', attack: 0.8, magic: 0.75, hp: 0.5, defense: 0.8, resist: 0.7, crit: 0.02, tier: 1, level: 10, requires: {vit: 14, luk: 14}, mastery: 0, role: '페널티·숙련', tree: 'mystery', hidden: true, penalties: {accuracy: -0.08}, masteryTarget: 10000000, masteryBoost: 0.16, hint: '몇 번이고 쓰러져 본 모험가에게 죽음이 말을 겁니다.'},
    {id: 'manaLeviathan', subRole: 'magic', name: '아델 (3차)', title: '세계 전체를 주문으로 삼킨다', desc: 'MP 비례 주문을 극단까지 밀어붙이는 환생 후 3차 히든 직업입니다.', attack: 0.92, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.12, bonus: {magic: 50, resist: 12}, tier: 3, level: 40, parent: 'voidcaller', requires: {int: 50, wis: 38}, mastery: 150, role: 'MP·히든', tree: 'mystery', lineage: 'voidcaller', hidden: true, rebirth: 3, requiresSkillMastery: {voidLance: 4}, requiresJobMastery: {tide: 150}, masteryTarget: 270000, masteryBoost: 0.4, hint: '공허와 마나를 모두 익히고 윤회를 거듭한 자에게.'},
    {id: 'voidSovereign', subRole: 'magic', name: '아델 (4차)', title: '비어 있음으로 채운다', desc: '공허 계보의 4차 히든 직업입니다. 칙령은 최대 마나를 쏟아부어 때리고, 패시브로 마나와 마법 공격을 올립니다.', attack: 1, magic: 1.52, hp: 1.18, defense: 1.12, resist: 1.21, crit: 0.12, tier: 4, level: 55, rebirth: 4, mastery: 300, masteryTarget: 300000, masteryBoost: 0.32, parent: 'manaLeviathan', requires: {int: 60, wis: 45}, requiresSkillMastery: {leviathanEquation: 3}, role: 'MP·최상위', tree: 'mystery', lineage: 'voidcaller', hidden: true, hint: '디바이드를 마치고 윤회를 거듭한 자에게.'},
    {id: 'voidIncarnate', subRole: 'magic', name: '아델 (5차)', title: '아무것도 없는 곳에서 모든 것이', desc: '최대 마나에 비례하는 인피니트와 거대한 마나·마법 공격 패시브로 아델 계보의 정점에 선 히든 5차 직업입니다.', attack: 1, magic: 1.75, hp: 1.18, defense: 1.08, resist: 1.3, crit: 0.12, tier: 5, level: 70, rebirth: 5, mastery: 300000, masteryTarget: 1500000, masteryBoost: 0.35, parent: 'voidSovereign', requires: {int: 74, wis: 56}, requiresSkillMastery: {abyssDecree: 3}, role: 'MP 최상위·히든', tree: 'mystery', lineage: 'voidcaller', hidden: true, hint: '거듭된 윤회 끝에 공허의 칙령이 완성될 때.'},
    {id: 'journeyman', subRole: 'utility', name: '떠돌이 모험가', title: '배운 것은 몸에 남는다', desc: '직업 다섯을 끝까지 숙달한 자에게 열리는 패시브 전용 직업. 두 패시브가 숙달한 직업 수에 비례해 자랍니다. 떠돌이의 요령을 끼면 방랑 계보에 있는 동안 다른 계보에서 가져온 스킬을 1 AP 싸게 장착합니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 10, mastery: 0, tree: 'mystery', lineage: 'wander', hidden: true, masteryTarget: 4000, masteryBoost: 0.15, bonus: {attack: 2, magic: 2, hp: 10}, requires: {str: 10, int: 10, vit: 10}, role: '숙달·누적', fullKit: true, hint: '여러 직업을 끝까지 숙달한 모험가에게.'},
    {id: 'polymath', subRole: 'utility', name: '만능 모험가', title: '여덟 가지 삶을 한 몸에', desc: '직업 열둘을 숙달한 떠돌이 모험가에게 열리는 2차급 독립 직업. 숙달한 직업 수에 비례하는 복합 일격과 패시브를 가집니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0.02, bonus: {attack: 4, magic: 4, hp: 20}, tier: 2, level: 25, mastery: 0, requires: {str: 20, int: 20, vit: 20}, requiresJobMastery: {journeyman: 4000}, requiresMastered: 12, role: '숙달·복합', tree: 'mystery', lineage: 'wander', hidden: true, fullKit: true, masteryTarget: 12000, masteryBoost: 0.2, hint: '떠돌이 모험가가 많은 삶을 숙달했을 때.'},
    {id: 'hundredLives', subRole: 'utility', name: '백수', title: '모든 생을 기억하는 모험가', desc: '직업 스물을 숙달한 자에게 열리는 3차급 독립 직업. 숙달한 직업 수만큼 강해지는 천 번의 삶과 패시브로 모든 숙련의 결산을 받습니다.', attack: 1, magic: 1, hp: 1.02, defense: 1, resist: 1, crit: 0.03, bonus: {attack: 12, magic: 12, hp: 60, defense: 3, resist: 3}, tier: 3, level: 40, mastery: 0, requires: {str: 30, int: 30, vit: 30}, requiresJobMastery: {polymath: 12000}, requiresMastered: 20, role: '숙달·결산', tree: 'mystery', lineage: 'wander', hidden: true, fullKit: true, masteryTarget: 120000, masteryBoost: 0.3, hint: '만능 모험가가 그보다 더 많은 삶을 숙달했을 때.'},
    {id: 'clockmaker', subRole: 'border', name: '제로 (1차)', title: '고장 난 시간을 고친다', desc: '알파(빠른 기술)와 베타(무거운 기술)를 번갈아 쓰면 피해가 커지는 시간 직업. 쓰러지기 직전에는 타임 리와인드로 나의 시간만 처음으로 되감습니다(전투당 1회). 끝까지 숙달하면 제로 (5차)로 가는 길이 열립니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, bonus: {attack: 2, magic: 2, hp: 5}, tier: 1, level: 10, mastery: 0, requires: {dex: 12, int: 10}, role: '시간·속도', tree: 'mystery', lineage: 'zero', hidden: true, fullKit: true, masteryTarget: 3000, masteryBoost: 0.2, hint: '사냥터에서 오랜 시간을 보낸 뒤, 시계 소리가 들립니다.'},
    {id: 'chronarch', subRole: 'border', name: '제로 (5차)', title: '멈춘 시간 속을 홀로 걷는다', desc: '제로 (1차)를 숙달하고 시간 기술을 모두 익힌 뒤, 윤회를 거듭한 자에게만 열리는 5차급 독립 직업. 타임 디스토션(확정 기절 · 베타)과 쉐도우 레인(확정 추가 행동 · 알파)을 번갈아 쓰며 전투의 시간을 지배합니다.', attack: 1.55, magic: 1.55, hp: 1.2, defense: 1.1, resist: 1.1, crit: 0.1, tier: 5, level: 70, rebirth: 4, mastery: 0, requires: {dex: 60, int: 50}, requiresJobMastery: {clockmaker: 3000}, requiresSkillMastery: {windUp: 4, slackHand: 4, timeMachine: 4}, role: '시간·제어', tree: 'mystery', lineage: 'zero', hidden: true, fullKit: true, masteryTarget: 1500000, masteryBoost: 0.35, hint: '시계의 모든 톱니를 맞추고 윤회를 거듭한 자에게.'},
    // v3.200 궁극의 모험가(옛 윤회의 나그네, id 그대로): 초보자 계보의 히든 5차. 숨은 조건(5차 직업 3개 숙달) + Lv.70 · 환생 10 · 계급장 하사 이상.
    // 고유 규칙: 다른 계보의 5차 전용 기술을 계승해 써도 효율이 깎이지 않습니다(signatureFree).
    {id: 'rebirthFisher', subRole: 'physical', name: '궁극의 모험가', title: '모든 모험의 끝에서 다시 처음으로', desc: '여러 직업의 정점에 서 본 모험가가 초보자의 길로 돌아와 닿는 히든 5차 직업. 다른 계보의 5차 전용 기술을 계승해 써도 효율이 깎이지 않습니다. 자기 각성기는 없고 궁극의 유산 하나만 가지며, 액티브는 다른 직업의 기술을 빌려 씁니다.', attack: 1.6, magic: 1.6, hp: 1.2, defense: 1.1, resist: 1.1, crit: 0.1, tier: 5, level: 70, rebirth: 10, mastery: 0, requires: {}, requiresRank: 'ssg', role: '궁극·모든 전용 기술', tree: 'mystery', lineage: 'fisher', hidden: true, signatureFree: true, masteryTarget: 1500000, masteryBoost: 0.35, hint: '여러 정점에 서 본 모험가에게, 처음의 걸음이 다시 보입니다.'},
    {id: 'hacker', subRole: 'none', name: '해커', title: '게임의 헛점을 파고든다', desc: '전투 능력은 전무합니다. 사냥·던전·결투·월드보스·신 도전에 참여할 수 없고, 능력치 투자와 해커 전용이 아닌 스킬 장착이 막히며, 해커로 있는 동안 레벨·경험치가 멈춥니다. 대신 침투 작전으로 비트와 권한을 쌓고, 서버의 방송을 탈취하고 다른 모험가의 숨김을 깨뜨립니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 1, level: 30, rebirth: 5, mastery: 0, requires: {}, role: '해킹·서버', tree: 'mystery', lineage: 'hacker', hidden: true, hint: '윤회를 거듭한 자에게 서버의 틈이 보입니다.', masteryTarget: 3000, masteryBoost: 0},
    {id: 'blackHacker', subRole: 'none', name: '블랙 해커', title: '흔적을 남기지 않는 자', desc: '해커와 같은 제약(전투 불가, 레벨·경험치 정지)을 받습니다. 해킹의 하루 횟수가 두 배(쿨다운 절반)지만 비트도 두 배로 들고, 해킹마다 실패 확률(35% − 단계×3%, 최소 5%)이 있습니다. 실패하면 비트·횟수만 쓰이고, 추적되어 소식에 이름이 공지되며 6시간 동안 해킹할 수 없습니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 2, level: 30, rebirth: 5, parent: 'hacker', mastery: 1500, requires: {}, role: '고위험 해킹', tree: 'mystery', lineage: 'hacker', hidden: true, hint: '해커로 서버를 충분히 들여다본 자에게 더 어두운 길이 보입니다.', masteryTarget: 6000, masteryBoost: 0},
    {id: 'whiteHacker', subRole: 'none', name: '화이트 해커', title: '뚫린 곳을 막는 자', desc: '해커와 같은 제약(전투 불가, 레벨·경험치 정지)을 받습니다. 공격 해킹(방송 탈취·크래킹·이벤트 변조·서버 다운) 대신 다른 해커의 해킹을 되돌리고(현상금으로 비트), 사냥터·던전을 패치해 한 시간 동안 서버 다운을 막습니다. 전용 패시브 방화벽은 하루 한 번 크래킹을 막아 냅니다.', attack: 1, magic: 1, hp: 1, defense: 1, resist: 1, crit: 0, tier: 2, level: 30, rebirth: 5, parent: 'hacker', mastery: 1500, requires: {}, role: '복구·패치', tree: 'mystery', lineage: 'hacker', hidden: true, hint: '해커로 서버를 충분히 들여다본 자에게 반대편 길이 보입니다.', masteryTarget: 6000, masteryBoost: 0},
    // v3.220 아제로스 히든 계보(세계: 아제로스). 처치 기록이 숨은 조건이고, 계보마다 그 기록에 비례해 자라는 패시브(perCount)를 가집니다.
    // v3.221 아제로스 규칙: 계급장 조건(4차 하사 · 칠흑의 화신 상사)과 숙련 ×10(AZEROTH_MASTERY_SCALE, register.ts).
    {id: 'kkamiHunter', requiresRank: 'ssg', subRole: 'physical', name: '까미 사냥꾼', title: '금빛 그림자를 쫓는 자', desc: '숙련의 까미를 수없이 쫓아 본 모험가의 아제로스 히든 4차 직업. 이 직업으로 있는 동안 까미가 1.5배 자주 나타나고, 황금 올가미로 까미를 빠르게 잡습니다. 까미를 잡은 횟수만큼 물리 공격과 치명타 확률이 자랍니다(100%를 넘은 치명타는 극 치명타로).', mimicFind: 0.5, attack: 1.5, magic: 1, hp: 1.15, defense: 1.1, resist: 1.1, crit: 0.12, tier: 4, level: 55, mastery: 0, requires: {dex: 60, luk: 45}, role: '히든·까미', tree: 'mystery', lineage: 'kkamiHunter', hidden: true, masteryTarget: 300000, masteryBoost: 0.32, hint: '금빛 그림자를 수없이 쫓아 본 모험가에게 낯선 대륙의 발자국이 보입니다.'},
    {id: 'nuriTracker', requiresRank: 'ssg', subRole: 'magic', name: '누리 추적자', title: '하얀 발자국을 읽는 자', desc: '경험의 누리를 수없이 추적해 본 모험가의 아제로스 히든 4차 직업. 이 직업으로 있는 동안 누리가 1.5배 자주 나타나고, 하얀 발자국으로 누리를 빠르게 잡습니다. 누리를 잡은 횟수만큼 마법 공격과 방어 관통이 자랍니다.', nuriFind: 0.5, attack: 1, magic: 1.5, hp: 1.15, defense: 1.08, resist: 1.15, crit: 0.1, tier: 4, level: 55, mastery: 0, requires: {int: 60, wis: 45}, role: '히든·누리', tree: 'mystery', lineage: 'nuriTracker', hidden: true, masteryTarget: 300000, masteryBoost: 0.32, hint: '하얀 빛을 수없이 쫓아 본 모험가에게 낯선 대륙의 길이 보입니다.'},
    {id: 'darkFollower', requiresRank: 'ssg', subRole: 'borderCore', name: '어둠의 추종자', title: '쓰러뜨린 군주들의 그림자를 거느린다', desc: '모든 지역 던전의 주인을 거듭 쓰러뜨린 모험가의 아제로스 히든 4차 직업. 이 직업으로 있는 동안 끼지 않은 지역 보스 코어의 공명이 10%에서 30%로 오릅니다. 보유한 지역 보스 코어 수만큼 어둠의 의식(자기 버프)과 패시브가 강해지고, 물리 · 마법 · 상태이상 · 회복 빌드 모두 같은 몫을 받습니다.', coreResonance: 0.3, attack: 1.3, magic: 1.3, hp: 1.2, defense: 1.12, resist: 1.12, crit: 0.06, tier: 4, level: 55, mastery: 0, requires: {vit: 60, wis: 45}, role: '히든·보스·코어', tree: 'mystery', lineage: 'darkFollower', hidden: true, masteryTarget: 300000, masteryBoost: 0.32, hint: '모든 던전의 주인이 그 이름을 기억할 때, 어둠이 손을 내밉니다.'},
    {id: 'onyxAvatar', requiresRank: 'msg', subRole: 'physical', name: '칠흑의 화신', title: '칠흑이 몸을 얻었다', desc: '칠흑의 보스를 거듭 쓰러뜨린 모험가의 아제로스 히든 5차 직업. 칠흑 보스를 잡은 횟수만큼 두 공격과 모든 능력치 배율이 자랍니다.', attack: 1.6, magic: 1.6, hp: 1.2, defense: 1.1, resist: 1.1, crit: 0.1, tier: 5, level: 70, mastery: 0, requires: {str: 55, int: 55}, role: '히든·칠흑', tree: 'mystery', lineage: 'onyxAvatar', hidden: true, masteryTarget: 1500000, masteryBoost: 0.35, hint: '칠흑의 군주들을 거듭 쓰러뜨린 자에게, 그 어둠이 깃듭니다.'},
];
export const SECRET_LINEAGES: Lineage[] = [
    // v3.135 나이트워커 계보 폐지: 2~5차 · 골령술사를 지우고 1차 망인(undead)만 제약 계보(data/specials.ts)로 돌려보냅니다.
    {id: 'voidcaller', name: '아델 계보', tree: 'mystery', summary: '환생 이후에 드러나는 마나 연소 히든 계보입니다. 고정 마나 소모 없이 현재 마나의 일부를 태워 그만큼 피해에 더하고, 큰 마나 통과 마나 회복이 연료가 됩니다.'},
    /** v3.65 숙달 사다리(떠돌이 → 만능 → 백수)를 ‘방랑’ 계보로, 제로를 자기 계보로 묶습니다. 은월은 공개 계보(classes.ts)로 옮겼습니다. */
    {id: 'wander', name: '방랑 계보', tree: 'mystery', summary: '여러 직업을 끝까지 숙달할수록 강해지는 숨은 계보입니다.'},
    {id: 'zero', name: '제로 계보', tree: 'mystery', summary: '역할의 경계에 선 숨은 계보입니다. 시간을 되감아 판을 다시 짭니다.'},
    // v3.220 아제로스(세계) 히든 계보.
    {id: 'kkamiHunter', name: '까미 사냥꾼 계보', tree: 'mystery', world: 'azeroth', summary: '숙련의 까미를 오래 사냥한 모험가의 계보입니다. 까미를 잡을수록 강해집니다.'},
    {id: 'nuriTracker', name: '누리 추적자 계보', tree: 'mystery', world: 'azeroth', summary: '경험의 누리를 오래 추적한 모험가의 계보입니다. 누리를 잡을수록 강해집니다.'},
    {id: 'darkFollower', name: '어둠의 추종자 계보', tree: 'mystery', world: 'azeroth', summary: '모든 지역 던전의 주인을 거듭 쓰러뜨린 모험가의 계보입니다. 던전을 정복할수록 보스에게 강해집니다.'},
    {id: 'onyxAvatar', name: '칠흑의 화신 계보', tree: 'mystery', world: 'azeroth', summary: '칠흑의 보스를 거듭 쓰러뜨린 모험가의 계보입니다. 칠흑 보스를 잡을수록 강해집니다.'},
    {id: 'hacker', name: '해커 계보', tree: 'mystery', summary: '전투 대신 침투 작전과 해킹으로 자라는 계보입니다. 화이트 해커는 해킹을 되돌리고 서버를 지키고, 블랙 해커는 더 자주·더 비싸게 해킹하다 추적당할 위험을 집니다.'},
];
