/**
 * v3.47 비밀 직업의 스킬(서버 전용, docs/concept.md 10장). 히든·??? 문 직업 스킬 67개를 완성된 모양 그대로 둡니다.
 * 이름·설명·수치(밸런스·숙련 목표·랭크 효과·메이플 이름·연출 갈래 fx)가 모두 여기 있고, 공개 표(skills.ts 등)에는 없습니다.
 * 서버가 register.ts로 스킬 표에 더하고, 화면은 카탈로그로 드러난 직업의 스킬만 받습니다.
 * 폭류권(tentacleBarrage)은 보스도 쓰는 공개 기술이라 공개 표에도 있지만, 숙련 목표가 비밀 직업의 차수로 정해지므로
 * 완성된 값을 여기에 두어 서버에서 덮어씁니다(화면은 그 직업이 드러나면 카탈로그로 받음).
 * 편집은 이 파일에서 합니다. 예전에 skills.ts 후처리를 거친 결과를 v3.47에 그대로 옮겼습니다.
 */
// v3.49 서버 전용 표식: 화면(클라이언트) 번들이 이 파일을 가져가면 빌드가 실패합니다(docs/concept.md 10.2-1).
import 'server-only';
import type { Skill } from '../types';

export const SECRET_SKILLS: Skill[] = [
    {id: 'voidLance', name: '샤드', desc: '(마법 공격 + 태운 마나 × 6) × 2 피해. 현재 마나의 12%를 태웁니다.', type: 'active', level: 25, rebirth: 2, job: 'voidcaller', chance: 0.55, cooldown: 4, multiplier: 2, damageType: 'magic', cost: 5, manaCost: 0, manaBurn: 0.12, rankEffects: {chanceIncrease: 0.025, manaReduction: 1, multiplierScale: 0.05, cooldownReduction: 0}, masteryMilestones: [1000, 6000, 22000, 60000]},
    {id: 'echoMemory', name: '에테르', desc: '마나 +60, 턴당 마나 회복 +6, 발동 확률 +4%p, 회피 +5%p.', type: 'passive', level: 25, rebirth: 2, job: 'voidcaller', chance: 0, cooldown: 0, multiplier: 0, cost: 3, bonus: {mana: 60, manaRegen: 6, accuracy: 0.04, evasion: 0.05}, rankEffects: {bonusScale: 0.3}, masteryMilestones: [600, 3000, 12000, 36000]},
    // v3.198 히든 리메이크: 무덤파기는 산 자의 생명을 긁어 오는 흡혈 일격(전에는 피해 없는 약화 5턴이라 깎인 몸으로 버틸 수단이 없었음).
    {id: 'graveHook', name: '무덤파기', desc: '(물리 공격) × 1.3 피해. 실제 피해의 25% 회복.', type: 'active', level: 10, job: 'undead', chance: 0.3, cooldown: 4, multiplier: 1.3, effect: 'drain', drainRatio: 0.25, damageType: 'physical', cost: 2, manaCost: 0, rankEffects: {multiplierScale: 0.05, chanceIncrease: 0.02, manaReduction: 0, cooldownReduction: 0}, masteryMilestones: [250, 1200, 4500, 14000], fx: 'bone'},
    // v3.139 이름 죽지않은 영혼, 화면 설명은 '쓸모없음'(disguise, 실제 효과는 그대로). v3.137 숙련 100만 · 400만 · 1,000만(AP 6 → 4 → 2 → -3).
    {id: 'boneLegacy', name: '죽지않은 영혼', disguise: '쓸모없음', desc: '기본: AP 6. 숙련할수록 현재 직업의 마이너스 보정을 되찾고 AP가 줄어듭니다(숙련 100만 15% · AP 4, 400만 50% · AP 2, 1,000만 100% · AP -3). 성장 Lv.3: 최대 체력 +450 · 물리 방어 +45 · 물리·마법 공격 +45. 음수 AP는 편성 여유를 늘립니다.', type: 'passive', level: 10, job: 'undead', chance: 0, cooldown: 0, multiplier: 0, cost: 6, levelEffects: [{cost: 6}, {cost: 4, penaltyRelief: 0.15}, {cost: 2, bonus: {hp: 100, defense: 12}, penaltyRelief: 0.5}, {cost: -3, bonus: {hp: 450, defense: 45, attack: 45, magic: 45}, penaltyRelief: 1}], rankEffects: {bonusScale: 0.3}, masteryMilestones: [1000000, 4000000, 10000000]},
    {id: 'leviathanEquation', name: '디바이드', desc: '(마법 공격 + 태운 마나 × 6) × 1.8 피해. 약화 효과. 현재 마나의 12%를 태웁니다.', type: 'active', level: 40, rebirth: 3, job: 'manaLeviathan', chance: 0.55, cooldown: 5, multiplier: 1.8, effect: 'weaken', damageType: 'magic', manaBurn: 0.12, cost: 6, manaCost: 0, rankEffects: {chanceIncrease: 0.025, manaReduction: 1, multiplierScale: 0.05, cooldownReduction: 0}, masteryMilestones: [7500, 45000, 150000, 300000]},
    {id: 'deepReservoir', name: '크리에이션', desc: '최대 마나 +150, 턴당 마나 회복 +16, 방어 관통 +8%p.', type: 'passive', level: 40, rebirth: 3, job: 'manaLeviathan', chance: 0, cooldown: 0, multiplier: 0, cost: 3, bonus: {mana: 150, manaRegen: 16, penetration: 0.08}, rankEffects: {bonusScale: 0.3}, masteryMilestones: [4500, 22500, 84000, 225000]},
    {type: 'active', damageType: 'magic', id: 'abyssDecree', name: '그레이브', desc: '(마법 공격 + 태운 마나 × 6) × 2.2 피해. 현재 마나의 15%를 태웁니다.', level: 55, job: 'voidSovereign', chance: 0.55, cooldown: 4, multiplier: 2.2, cost: 5, manaCost: 0, manaBurn: 0.15, masteryMilestones: [25000, 120000, 400000, 1000000], rankEffects: {multiplierScale: 0.05, chanceIncrease: 0.025, manaReduction: 1, cooldownReduction: 0}},
    {type: 'passive', chance: 0, cooldown: 0, multiplier: 0, rankEffects: {bonusScale: 0.3}, id: 'silentAbyss', name: '레조넌스', desc: '최대 마나 · 마나 회복 · 마법 공격이 오릅니다.', level: 55, job: 'voidSovereign', cost: 3, bonus: {mana: 200, manaRegen: 16, magic: 36}, masteryMilestones: [25000, 120000, 400000, 1000000]},
    // v3.198 아델 하향: 디바이드 2.5 → 1.8(연소 15 → 12%) · 그레이브 2.6 → 2.2(3 · 4차가 같은 차수 중앙값의 2.6 · 1.9배).
    {type: 'active', damageType: 'magic', id: 'voidCollapse', name: '인피니트', desc: '(마법 공격 + 태운 마나 × 6) × 3.8 피해. 현재 마나의 30%를 태웁니다.', level: 70, job: 'voidIncarnate', chance: 0.55, cooldown: 5, multiplier: 3.8, cost: 6, manaCost: 0, manaBurn: 0.3, masteryMilestones: [100000, 450000, 1500000, 3750000], rankEffects: {multiplierScale: 0.05, chanceIncrease: 0.025, manaReduction: 1, cooldownReduction: 0}},
    // v3.124 아델 상향: 루인 마법 공격 +100 → +450(숙련 보정 뒤 엔드 마법 약 +26%, 썬콜 · 칼리와 같은 방식), 최대 마나 +150 → +1000(마나 비례 기술 · 마나 운용).
    {type: 'passive', chance: 0, cooldown: 0, multiplier: 0, rankEffects: {bonusScale: 0.3}, id: 'endlessVoid', name: '루인', desc: '최대 마나와 마법 공격이 크게 오르고 마나 회복이 오릅니다. 태울 마나가 곧 화력입니다.', level: 70, job: 'voidIncarnate', cost: 3, bonus: {mana: 1000, magic: 450, manaRegen: 30}, masteryMilestones: [100000, 450000, 1500000, 3750000]},
    {type: 'passive', chance: 0, cooldown: 0, multiplier: 0, id: 'thousandHands', name: '천 개의 손놀림', desc: '숙달한 직업 1개마다 두 공격 +3·최대 체력 +12·두 방어 +1(최대 60회).', level: 10, job: 'journeyman', cost: 3, perCount: [{source: 'mastered', per: 1, bonus: {attack: 3, magic: 3, hp: 12, defense: 1, resist: 1}, cap: 60}], masteryMilestones: [800, 4000, 16000, 50000], rankEffects: undefined},
    {type: 'active', chance: 0.45, cooldown: 4, multiplier: 1.2, id: 'borrowedForm', name: '배운 대로', desc: '(물리 공격) × 1.2 피해.', level: 25, job: 'polymath', cost: 4, damageType: 'split', scaling: 'mastered', scalingRatio: 0.03, manaCost: 32, masteryMilestones: [1500, 7000, 25000, 80000], rankEffects: {multiplierScale: 0.05, chanceIncrease: 0.025, manaReduction: 1, cooldownReduction: 0}, fx: 'arcane'},
    {type: 'passive', chance: 0, cooldown: 0, multiplier: 0, id: 'hundredKnacks', name: '백 가지 요령', desc: '숙달한 직업 1개마다 두 공격 +5·최대 체력 +20·두 방어 +1.5(최대 60회).', level: 25, job: 'polymath', cost: 3, perCount: [{source: 'mastered', per: 1, bonus: {attack: 5, magic: 5, hp: 20, defense: 1.5, resist: 1.5}, cap: 60}], masteryMilestones: [1500, 7000, 25000, 80000], rankEffects: undefined},
    // v3.198 백수 상향: 천 번의 삶 ×1.6 → ×2 · 숙달 직업당 +4 → +5%(전직 조건 15개 숙달 몸으로 재도 3차 중앙값의 0.6배였음).
    {type: 'active', chance: 0.45, cooldown: 5, multiplier: 2, id: 'thousandLives', name: '천 번의 삶', desc: '(물리 공격) × 2 피해. 약화 효과.', level: 40, job: 'hundredLives', cost: 5, damageType: 'split', scaling: 'mastered', scalingRatio: 0.05, effect: 'weaken', manaCost: 48, masteryMilestones: [7500, 36000, 120000, 300000], rankEffects: {multiplierScale: 0.05, chanceIncrease: 0.025, manaReduction: 1, cooldownReduction: 0}, statusTurns: 3, fx: 'star'},
    {type: 'passive', chance: 0, cooldown: 0, multiplier: 0, id: 'everyLife', name: '모든 생의 기억', desc: '최대 체력 +100. 숙달한 직업 1개마다 치명타·명중 +0.4%p·속도 +0.5·최대 체력 +15(최대 60회).', level: 40, job: 'hundredLives', cost: 3, bonus: {hp: 100}, perCount: [{source: 'mastered', per: 1, bonus: {crit: 0.004, accuracy: 0.004, speed: 0.5, hp: 15}, cap: 60}], masteryMilestones: [7500, 36000, 120000, 300000], rankEffects: undefined},
    // v3.198 히든 리메이크(방랑, 기록 비례형): 배운 것은 몸에 남는다 — 방랑 계보에서는 다른 계보 스킬을 1 AP 싸게 장착합니다.
    {type: 'passive', chance: 0, cooldown: 0, multiplier: 0, id: 'wayfarerKnack', name: '떠돌이의 요령', desc: '숙달한 직업 2개마다 치명타·명중 +1%p·속도 +1(최대 30회). 방랑 계보 직업일 때 다른 계보에서 가져온 스킬의 AP가 1 줄어듭니다(최소 1).', level: 10, job: 'journeyman', cost: 2, borrowedDiscount: 1, perCount: [{source: 'mastered', per: 2, bonus: {crit: 0.01, accuracy: 0.01, speed: 1}, cap: 30}], masteryMilestones: [800, 4000, 16000, 50000], rankEffects: undefined},
    // v3.198 히든 리메이크(제로, 경계형): 알파(빠른 기술) · 베타(무거운 기술)를 번갈아 쓰면 태그 패시브만큼 피해가 커집니다. 타임 리와인드는 나만 되감습니다.
    {type: 'active', chance: 0.3, cooldown: 3, multiplier: 1, damageType: 'physical', manaCost: 0, id: 'windUp', name: '문 스트라이크', desc: '(물리 공격) × 1 피해. 가속 효과. 태그: 알파.', level: 10, job: 'clockmaker', cost: 2, effect: 'haste', tag: 'alpha', rankEffects: {multiplierScale: 0.05, chanceIncrease: 0.02, manaReduction: 0, cooldownReduction: 0}, masteryMilestones: [250, 1200, 4500, 14000], fx: 'time'},
    {type: 'active', chance: 0.28, cooldown: 4, multiplier: 1.3, damageType: 'physical', manaCost: 0, id: 'slackHand', name: '피어스 쓰러스트', desc: '(물리 공격) × 1.3 피해. 감속 효과. 태그: 베타.', level: 10, job: 'clockmaker', cost: 2, effect: 'slow', tag: 'beta', rankEffects: {multiplierScale: 0.05, chanceIncrease: 0.02, manaReduction: 0, cooldownReduction: 0}, masteryMilestones: [250, 1200, 4500, 14000], fx: 'time'},
    {type: 'passive', chance: 0, cooldown: 0, multiplier: 0, id: 'timeLag', name: '타임 홀딩', desc: '속도와 회피가 오릅니다. 알파 · 베타 기술을 번갈아 쓰면 피해 +20%.', level: 10, job: 'clockmaker', cost: 2, bonus: {speed: 6, evasion: 0.02}, tagBonus: 0.2, rankEffects: undefined, masteryMilestones: [250, 1200, 4500, 14000]},
    {type: 'active', chance: 0.6, cooldown: 1, multiplier: 0, damageType: 'physical', manaCost: 0, id: 'timeMachine', name: '타임 리와인드', desc: '체력이 낮을 때 피해 없이 내 체력·마나를 가득 채우고 대기 중인 내 기술을 되돌립니다. 전투당 1회.', level: 10, job: 'clockmaker', cost: 2, timeRewind: true, condition: 'wounded', statusOnly: true, rankEffects: {multiplierScale: 0.05, chanceIncrease: 0.01, manaReduction: 0, cooldownReduction: 0}, masteryMilestones: [250, 1200, 4500, 14000], fx: 'time'},
    {type: 'active', chance: 1, cooldown: 6, multiplier: 5.2, id: 'frozenTime', name: '타임 디스토션', desc: '((물리 + 마법 공격) ÷ 2) × 5.2 피해. 기절 효과. 반드시 명중합니다. 태그: 베타.', level: 70, job: 'chronarch', cost: 5, damageType: 'split', scaling: 'dual', effect: 'stun', tag: 'beta', masteryMilestones: [25000, 120000, 400000, 1000000], rankEffects: {multiplierScale: 0.05, chanceIncrease: 0.025, manaReduction: 1, cooldownReduction: 0}, statusTurns: 2, manaCost: 32, sureHit: true, fx: 'time'},
    {type: 'active', chance: 0.45, cooldown: 5, multiplier: 5.5, id: 'precede', name: '쉐도우 레인', desc: '((물리 + 마법 공격) ÷ 2) × 5.5 피해. 곧바로 한 번 더 행동합니다. 태그: 알파.', level: 70, job: 'chronarch', cost: 5, damageType: 'split', scaling: 'dual', extraTurn: true, tag: 'alpha', masteryMilestones: [25000, 120000, 400000, 1000000], rankEffects: {multiplierScale: 0.05, chanceIncrease: 0.025, manaReduction: 1, cooldownReduction: 0}, manaCost: 32, fx: 'time'},
    {type: 'active', chance: 0.45, cooldown: 6, multiplier: 4.2, id: 'rewind', name: '리와인드', desc: '((물리 + 마법 공격) ÷ 2) × 4.2 피해. 최대 체력 35% 회복.', level: 70, job: 'chronarch', cost: 4, damageType: 'split', scaling: 'dual', effect: 'heal', masteryMilestones: [25000, 120000, 400000, 1000000], rankEffects: {multiplierScale: 0.05, chanceIncrease: 0.025, manaReduction: 1, cooldownReduction: 0}, healRatio: 0.35, manaCost: 32, fx: 'time'},
    {type: 'passive', chance: 0, cooldown: 0, multiplier: 0, id: 'chronoSovereign', name: '얼티밋 타임', desc: '속도·회피·치명타·명중이 크게 오르고, 연속 행동마다 편성 첫 번째 대기 중인 기술을 초기화합니다. 알파 · 베타 기술을 번갈아 쓰면 피해 +50%.', level: 70, job: 'chronarch', cost: 3, bonus: {speed: 18, evasion: 0.05, crit: 0.05, accuracy: 0.05, attack: 600, magic: 600}, tagBonus: 0.5, cooldownReset: {on: 'chain', chance: 1, pick: 'first'}, masteryMilestones: [25000, 120000, 400000, 1000000], rankEffects: undefined},
    // v3.200 궁극의 모험가(옛 윤회의 나그네): 자체 각성기 없이 궁극의 유산(두 공격 · 체력 패시브) 하나. 액티브는 다른 계보의 5차 기술을 빌려 씁니다.
    {id: 'ultimateLegacy', name: '궁극의 유산', desc: '물리 · 마법 공격과 최대 체력이 크게 오르고, 치명타 · 명중이 오릅니다.', type: 'passive', level: 70, job: 'rebirthFisher', chance: 0, cooldown: 0, multiplier: 0, cost: 3, bonus: {attack: 700, magic: 700, hp: 600, crit: 0.05, accuracy: 0.05}, rankEffects: {bonusScale: 0.3}, masteryMilestones: [100000, 450000, 1500000, 3750000]},
    {id: 'adGuard', name: '신원 조작', desc: '해커 전용. 고른 모험가 한 명(나도 가능)의 랭킹 정보 공개 여부를 바꿉니다. 숙련 1단계: 이름과 모든 정보를 ???로 1시간 가림. 숙련 2단계: 가릴 항목을 고름. 숙련 3단계: 가린 이름·직업·레벨 자리에 미끼 정보(가짜 값)를 보여 줌. 하루 횟수는 숙련 단계만큼. 크래킹을 당하면 그동안 풀립니다.', type: 'passive', level: 30, job: 'hacker', chance: 0, cooldown: 0, multiplier: 0, cost: 5, bonus: {}, masteryMilestones: [250, 1200, 4500, 14000], rankEffects: undefined},
    {id: 'firewall', name: '방화벽', desc: '하루 한 번, 나를 노린 크래킹을 막아 냅니다. 숙련은 해커 활동으로 오릅니다.', type: 'passive', level: 30, job: 'whiteHacker', chance: 0, cooldown: 0, multiplier: 0, cost: 3, bonus: {}, masteryMilestones: [250, 1200, 4500, 14000], rankEffects: undefined},
    {id: 'wipeTrace', name: '흔적 지우기', desc: '해킹에 실패해 추적당했을 때 해킹할 수 없는 시간이 6시간에서 3시간으로 줄어듭니다.', type: 'passive', level: 30, job: 'blackHacker', chance: 0, cooldown: 0, multiplier: 0, cost: 3, bonus: {}, masteryMilestones: [250, 1200, 4500, 14000], rankEffects: undefined},
    // v3.220 아제로스 히든 계보: 액티브 하나 + 처치 기록 비례 패시브 하나.
    // v3.221 까미 사냥꾼: 황금 올가미는 까미(대왕 포함)에게만 나가는 최대 체력 비례 고정 피해 + 숙련 로또 상향 표식. 패시브는 물리 공격 · 치명타 확률(100% 초과분은 극 치명타).
    {id: 'goldenSnare', name: '황금 올가미', desc: '숙련의 까미 · 대왕 까미에게만 발동합니다. 대상 최대 체력의 40% 고정 피해(방어 · 치명타 무시). 반드시 명중합니다. 올가미에 걸린 까미를 잡으면 25% 확률로 숙련 로또가 한 단계 위로 굴러갑니다(소 → 중, 중 → 대). 까미 사냥꾼 전용(궁극의 모험가는 예외).', type: 'active', level: 55, job: 'kkamiHunter', chance: 1, cooldown: 2, multiplier: 1, condition: 'kkami', exclusiveLineage: 'kkamiHunter', exclusiveUltimate: true, maxHpDamage: 0.4, jackpotUp: 0.25, sureHit: true, damageType: 'fixed', cost: 5, manaCost: 24, rankEffects: {multiplierScale: 0, chanceIncrease: 0, manaReduction: 1, cooldownReduction: 0}, masteryMilestones: [25000, 120000, 400000, 1000000]},
    {id: 'kkamiLedger', name: '까미 사냥 일지', desc: '물리 공격과 치명타 확률이 오르고, 숙련의 까미를 잡을수록 물리 공격과 치명타 확률이 더 오릅니다(300회에 치명타 +300%p). 100%를 넘은 치명타 확률은 100%p마다 극 치명타 확률 +5%가 됩니다.', type: 'passive', level: 55, job: 'kkamiHunter', chance: 0, cooldown: 0, multiplier: 0, cost: 3, bonus: {attack: 40, crit: 0.1}, perCount: [{source: 'kkami', per: 1, bonus: {attack: 2, crit: 0.01}, cap: 300}], rankEffects: {bonusScale: 0.3}, masteryMilestones: [25000, 120000, 400000, 1000000]},
    // v3.221 누리 추적자: 하얀 발자국은 누리(대왕 포함) 전용 최대 체력 비례 고정 피해 + 경험치 로또 상향 표식(누리 추적자 계보 전용, 궁극의 모험가 예외). 패시브는 마법 공격 · 방어 관통.
    {id: 'whiteTrail', name: '하얀 발자국', desc: '경험의 누리 · 대왕 누리에게만 발동합니다. 대상 최대 체력의 40% 고정 피해(방어 · 치명타 무시). 반드시 명중합니다. 발자국이 남은 누리를 잡으면 25% 확률로 경험치 로또가 한 단계 위로 굴러갑니다(소 → 중, 중 → 대). 누리 추적자 전용(궁극의 모험가는 예외).', type: 'active', level: 55, job: 'nuriTracker', chance: 1, cooldown: 2, multiplier: 1, condition: 'nuri', exclusiveLineage: 'nuriTracker', exclusiveUltimate: true, maxHpDamage: 0.4, jackpotUp: 0.25, sureHit: true, damageType: 'fixed', baseStat: 'magic', cost: 5, manaCost: 30, rankEffects: {multiplierScale: 0, chanceIncrease: 0, manaReduction: 1, cooldownReduction: 0}, masteryMilestones: [25000, 120000, 400000, 1000000]},
    {id: 'nuriChronicle', name: '누리 추적 기록', desc: '마법 공격과 방어 관통이 오르고, 경험의 누리를 잡을수록 마법 공격과 방어 관통이 더 오릅니다(300회에 관통 +30%p, 관통 합계 상한 85%).', type: 'passive', level: 55, job: 'nuriTracker', chance: 0, cooldown: 0, multiplier: 0, cost: 3, bonus: {magic: 40, penetration: 0.05}, perCount: [{source: 'nuri', per: 1, bonus: {magic: 2, penetration: 0.001}, cap: 300}], rankEffects: {bonusScale: 0.3}, masteryMilestones: [25000, 120000, 400000, 1000000]},
    // v3.221 어둠의 추종자: 어둠의 의식은 보유한 지역 보스 코어 수(무릉도장 코어 제외, 최대 7)에 비례하는 자기 버프(피해 없음). 직접 피해 · 지속 피해 · 회복을 같은 몫으로 올려 물리 · 마법 · 상태이상 · 회복 빌드 모두 손해가 없습니다.
    {id: 'shadowRite', name: '어둠의 의식', desc: '피해 없이 자기 버프 ‘군주의 그림자’(4턴)를 겁니다. 보유한 지역 보스 코어 1개마다 주는 직접 피해 · 지속 피해 · 회복량 +7%(7개 +49%). 코어 3개 이상: 6턴. 5개 이상: 쓸 때 2턴 상태이상 면역. 7개: 쓰고 곧바로 한 번 더 행동. 어둠의 추종자 전용(궁극의 모험가는 예외).', type: 'active', level: 55, job: 'darkFollower', chance: 1, cooldown: 8, multiplier: 0, statusOnly: true, sureHit: true, damageType: 'physical', exclusiveLineage: 'darkFollower', exclusiveUltimate: true, coreBuff: {id: 'lordShadow', name: '군주의 그림자', turns: 4, damage: 0.07, stats: {dotBonus: 0.07, healBonus: 0.07}, steps: [{at: 3, turns: 6}, {at: 5, wardTurns: 2}, {at: 7, extraTurn: true}]}, cost: 5, manaCost: 24, rankEffects: {multiplierScale: 0, chanceIncrease: 0, manaReduction: 1, cooldownReduction: 0}, masteryMilestones: [25000, 120000, 400000, 1000000], fx: 'bone'},
    {id: 'fallenLords', name: '쓰러진 군주들', desc: '최대 마나와 보스 피해가 오르고, 보유한 지역 보스 코어 1개마다 보스 피해 +3% · 지속 피해 +4% · 회복량 +4% · 상태이상 저항 +3%p, 코어 각성 1단계마다 공격 · 방어 배율 +0.3%(체력 제외)가 더 오릅니다.', type: 'passive', level: 55, job: 'darkFollower', chance: 0, cooldown: 0, multiplier: 0, cost: 3, bonus: {mana: 150, bossDamage: 0.1}, perCount: [{source: 'cores', per: 1, bonus: {bossDamage: 0.03, dotBonus: 0.04, healBonus: 0.04, statusResist: 0.03}, cap: 7}, {source: 'coreRanks', per: 1, bonus: {combatScale: 0.003}, cap: 35}], rankEffects: {bonusScale: 0.3}, masteryMilestones: [25000, 120000, 400000, 1000000]},
    // v3.221 칠흑의 화신: 칠흑 일식은 물리 · 마법 중 높은 쪽(bestOf), 끼고 있는 칠흑 장신구의 보스마다 효과 하나(onyxForms). 칠흑의 화신 전용(궁극의 모험가 예외).
    // 패시브는 체력 대신 고정 마나, 보유 칠흑 · 각성 비례 공격 · 방어 배율(combatScale, 체력 제외), 칠흑 처치 비례 보스 피해.
    {id: 'onyxEclipse', name: '칠흑 일식', desc: '(물리 · 마법 공격 중 높은 쪽) × 4.5 피해(그 종류로 방어 적용). 끼고 있는 칠흑 장신구에 따라: 더스크 3턴 반격 강화 · 듄켈 3턴 연속 행동 확률 +30%p · 윌 기절 1턴 · 루시드 약화 2턴 · 진 힐라 실제 피해의 30% 회복 · 세렌 보스 · 사냥감 피해 +50% · 검은 마법사 3턴 주는 피해 ×1.3. 칠흑의 화신 전용(궁극의 모험가는 예외).', type: 'active', level: 70, job: 'onyxAvatar', chance: 0.45, cooldown: 5, multiplier: 4.5, bestOf: true, damageType: 'physical', exclusiveLineage: 'onyxAvatar', exclusiveUltimate: true, onyxForms: {onyxDusk: {selfBuff: {id: 'duskFear', name: '공포의 가시', turns: 3, stats: {thorns: 0.3}}}, onyxDunkel: {selfBuff: {id: 'commanderBeat', name: '지휘관의 박자', turns: 3, stats: {chainBonus: 0.3}}}, onyxWill: {effect: 'stun', statusTurns: 1}, onyxLucid: {effect: 'weaken', statusTurns: 2}, onyxHilla: {effect: 'drain', drainRatio: 0.3}, onyxSeren: {preyBonus: 0.5}, onyxBlackMage: {selfBuff: {id: 'genesis', name: '창세', turns: 3, damageMultiplier: 1.3}}}, cost: 5, manaCost: 32, rankEffects: {multiplierScale: 0.05, chanceIncrease: 0.025, manaReduction: 1, cooldownReduction: 0}, masteryMilestones: [100000, 450000, 1500000, 3750000]},
    {id: 'onyxHeart', name: '칠흑의 심장', desc: '최대 마나와 보스 피해가 오르고, 보유한 칠흑 장신구 1종마다 공격 · 방어 배율 +2%, 칠흑 각성 1단계마다 공격 · 방어 배율 +0.3%, 칠흑 보스 10회 처치마다 보스 피해 +1%가 더 오릅니다. 공격 · 방어 배율은 물리/마법 공격과 물리/마법 방어에만 붙고 체력은 오르지 않습니다.', type: 'passive', level: 70, job: 'onyxAvatar', chance: 0, cooldown: 0, multiplier: 0, cost: 3, bonus: {mana: 300, bossDamage: 0.1}, perCount: [{source: 'onyxOwned', per: 1, bonus: {combatScale: 0.02}, cap: 7}, {source: 'onyxRanks', per: 1, bonus: {combatScale: 0.003}, cap: 35}, {source: 'onyx', per: 10, bonus: {bossDamage: 0.01}, cap: 30}], rankEffects: {bonusScale: 0.3}, masteryMilestones: [100000, 450000, 1500000, 3750000]},
];
