// 게임플레이 테스트 공용 준비: 게임 모듈, 공유 시드 난수, test 함수. 테스트 파일은 run.mjs가 정한 순서로 실행됩니다(난수 상태를 공유).
import {readFile} from 'node:fs/promises';
import { loadGame } from '../scripts/lib/game-modules.mjs';
import assert from 'node:assert/strict';
export { assert };
const {load}=loadGame();
export const {newState,act,advance,tick,victoryHeal,rollRarity}=await load('game/systems/engine.js');
export const encounterSource=await readFile('game/systems/encounter.ts','utf8');
export const {stats,snapshot,expMultiplier,normalizeStats}=await load('game/systems/stats.js');
export const {victoryMastery}=await load('game/systems/mastery.js');
export const {visibleStatuses}=await load('game/systems/combat-status.js');
export const {duel,TRAINING}=await load('game/systems/duel.js');
export const {strike,fighterSpeed}=await load('game/systems/combat.js');
export const {combatFxFromLog,combatFxBatch}=await load('game/systems/combat-feedback.js');
export const {migrateState}=await load('game/systems/migrations.js');
export const {apCapacity,apUsed,canUse,canChangeJob,effectiveSkill,skillRankDeltas,skillMasteryLevel,masteryMilestonesFor,jobRequirements,validLoadout,skillLevel,maxSkillLevel,inherited,trimLoadout,jobMasteryTarget,jobCombatMultiplier}=await load('game/systems/progression.js');
export const {goalProgress,goalSuggestions}=await load('game/systems/goals.js');
export const {skillGrowthStages}=await load('game/systems/skill-description.js');
export const {SKILLS}=await load('game/data/skills.js');
export const {STAGES,FISH,DUNGEONS}=await load('game/data/world.js');
export const {profile}=await load('game/data/encounters.js');
export const bookMod=await load('game/systems/book.js');
export const economy=await load('game/data/economy.js');
export const {researchRefund}=await load('game/systems/commerce.js');
export const {weightedFishId}=await load('game/systems/encounter.js');
export const {shopCost,gambleCost,shopPreview}=await load('game/systems/commerce.js');
export const {itemStats,enhanceCost,bulkItems}=await load('game/systems/equipment.js');
export const {goldMultiplier,dungeonGoldMultiplier,dropRate,hitChance}=await load('game/systems/stats.js');
export const {rebirthLevel,rebirthReward}=await load('game/systems/meta.js');
export const metaMod=await load('game/systems/meta.js');
export const longTerm=await load('game/data/long-term.js');
export const {xpNeeded,SKILL_FORMULA,STATUS_TUNING,BALANCE,RARITIES}=await load('game/data/balance.js');
export const STATUS_TUNING_MAX=STATUS_TUNING.poisonMaxStacks;
export const gear=await load('game/data/gear.js');
export const {PROGRESSION}=await load('game/data/progression.js');
export const {JOBS,JOB_TREES}=await load('game/data/classes.js');
let seed=44;
export const rng=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);
export const results={passed:0};
export const test=(name,fn)=>{fn();results.passed++;console.log('PASS',name)};
