// 세이브·장비·환생·던전·결투·전투 판정·경제·길드
import { newState, act, tick, stats, snapshot, expMultiplier, duel, TRAINING, strike, fighterSpeed, migrateState, apCapacity, SKILLS, FISH, DUNGEONS, profile, shopCost, gambleCost, shopPreview, itemStats, enhanceCost, bulkItems, goldMultiplier, dungeonGoldMultiplier, dropRate, hitChance, rebirthLevel, rebirthReward, xpNeeded, assert, rng, test, effectiveSkill, BALANCE } from './harness.mjs';
test('Saves from before v8 restart fresh, keep only the name, and are idempotent',()=>{const s=newState(0);s.version=7;s.name='오래된 낚시꾼';s.level=60;s.gold=99999;s.pearls=500;s.upgrades={attack:30};s.rebirths=4;migrateState(s,5000);const fresh=newState(5000);fresh.name='오래된 낚시꾼';assert.deepEqual(s,fresh);assert.equal(s.version,8);assert.equal(s.upgrades,undefined);const saved=JSON.stringify(s);migrateState(s,9000);assert.equal(JSON.stringify(s),saved);const v1=newState(0);v1.version=1;delete v1.guild;migrateState(v1,0);assert.equal(v1.version,8);assert.ok(v1.guild);});
test('Equipment swapping preserves item counts and sale is single-use',()=>{const s=newState(0);s.inventory.push({id:'test',name:'Test',slot:'rod',rarity:2,power:20,level:1});act(s,{type:'equip',id:'test'},0);assert.equal(s.equipment.rod.id,'test');assert.equal(s.inventory.length,1);act(s,{type:'sell',id:'starter'},0);assert.throws(()=>act(s,{type:'sell',id:'starter'},0));assert.equal(s.inventory.length,0)});
test('Gold training is removed: the upgrade action is rejected and research still costs pearls',()=>{const s=newState(0);const gold=s.gold;assert.throws(()=>act(s,{type:'upgrade',id:'attack'},0));assert.equal(s.gold,gold);assert.equal(s.upgrades,undefined);assert.throws(()=>act(s,{type:'permanent',id:'attack'},0));});
test('Rebirth resets run while preserving permanent progression',()=>{const s=newState(0);s.level=30;s.job='harpoon';s.gold=999;s.book={minnow:50};s.permanent.attack=2;s.pearls=1;s.clears.grotto=1;s.skills=['pierce'];act(s,{type:'rebirth'},100);assert.equal(s.level,1);assert.equal(s.job,'fisher');assert.equal(s.gold,100);assert.equal(s.pearls,4);assert.equal(s.rebirths,1);assert.equal(s.book.minnow,50);assert.equal(s.permanent.attack,2);assert.equal(s.clears.grotto,1);assert.deepEqual(s.skills,['hook']);assert.equal(s.hp,stats(s).hp)});
test('Dungeon completion and first-clear pearl only once',()=>{const s=newState(0);s.level=40;s.permanent.attack=40;s.permanent.hp=40;act(s,{type:'dungeon',id:'grotto'},0);for(let i=0;i<100&&s.running;i++)tick(s,rng);assert.equal(s.clears.grotto,1);assert.equal(s.pearls,1);assert.equal(s.dungeon,null);assert.equal(s.running,false);act(s,{type:'dungeon',id:'grotto'},0);for(let i=0;i<100&&s.running;i++)tick(s,rng);assert.equal(s.clears.grotto,2);assert.equal(s.pearls,1)});
test('PvP is isolated from PvE, bounded and deterministic',()=>{const s=newState(0),before=JSON.stringify(s);let fixed=()=>.9;const result=duel(snapshot(s),TRAINING[0],true,fixed);assert.equal(JSON.stringify(s),before);assert.ok(result.turns<=80);assert.equal(result.ratingChange,0);assert.deepEqual(result,duel(snapshot(s),TRAINING[0],true,fixed));assert.ok(result.logs.length>0)});
test('Stun skips enemy action and cooldown prevents instant repeated proc',()=>{const st={hp:1000,attack:10,defense:0,crit:0};const a={name:'A',stats:st,hp:1000,skills:['splash'],cooldowns:{},stun:0},b={name:'B',stats:st,hp:1000,skills:[],cooldowns:{},stun:0};assert.match(strike(a,b,()=>0),/물보라/);assert.equal(b.stun,1);assert.match(strike(b,a,()=>0),/행동 불가/);assert.equal(a.hp,1000);assert.match(strike(a,b,()=>0),/기본 공격/)});
test('Mana budget, magic defense, accuracy and damage over time',()=>{const cost=effectiveSkill(SKILLS.find(x=>x.id==='arcane'),1).manaCost;assert.ok(cost>0);const make=(extra={})=>({name:'test',stats:{hp:1000,attack:20,magic:100,defense:0,resist:0,crit:0,mana:cost*2,manaRegen:0,...extra},hp:1000,skills:['arcane'],cooldowns:{},stun:0,mana:cost*2,effects:{}});let a=make(),b=make({defense:1000});assert.match(strike(a,b,()=>0),/마법/);assert.equal(b.hp,845);assert.equal(a.mana,cost);a=make();a.mana=0;assert.match(strike(a,make(),()=>0),/기본 공격/);assert.match(strike(make(),make(),()=>.999),/빗나감/);a=make();a.hp=5;a.effects={dot:{damage:10,turns:1,name:'출혈'}};b=make();assert.match(strike(a,b,()=>0),/쓰러짐/);assert.equal(a.hp,0);assert.equal(b.hp,1000);});
test('Silence blocks active skills but keeps basic attacks',()=>{const st={hp:1000,attack:20,magic:100,defense:0,resist:0,crit:0,mana:1000,manaRegen:0};const caster={name:'Caster',stats:st,hp:1000,skills:['hushCurrent'],cooldowns:{},stun:0,mana:1000,effects:{}};const target={name:'Target',stats:st,hp:1000,skills:['splash'],cooldowns:{},stun:0,mana:1000,effects:{}};assert.match(strike(caster,target,()=>0),/침묵 2턴/);assert.equal(target.effects.silence,2);const before=caster.hp;const log=strike(target,caster,()=>0);assert.match(log,/침묵 중/);assert.match(log,/기본 공격/);assert.doesNotMatch(log,/물보라/);assert.ok(caster.hp<before);assert.equal(target.cooldowns.splash,undefined);});
test('Slow and haste change round priority without adding actions',()=>{const st={hp:1000,attack:10,defense:0,crit:0,speed:20};const normal={name:'normal',stats:st,hp:1000,skills:[],cooldowns:{},stun:0,effects:{}};const slow={...normal,name:'slow',effects:{slow:3}};const haste={...normal,name:'haste',effects:{haste:3}};assert.ok(fighterSpeed(slow)<fighterSpeed(normal));assert.ok(fighterSpeed(haste)>fighterSpeed(normal));assert.equal(Math.round(fighterSpeed(slow)),13);assert.equal(Math.round(fighterSpeed(haste)),27);});
test('Extra attacks are data-driven and capped',()=>{const st={hp:1000,attack:70,defense:0,crit:0,mana:1000,manaRegen:0};const a={name:'연타자',stats:st,hp:1000,skills:['twinHook'],cooldowns:{},stun:0,mana:1000,effects:{}};const b={name:'표적',stats:st,hp:1000,skills:[],cooldowns:{},stun:0,mana:1000,effects:{}};const log=strike(a,b,()=>0);assert.match(log,/쌍갈고리/);assert.match(log,/추가타/);assert.ok(b.hp<900);assert.ok(SKILLS.find(x=>x.id==='tentacleBarrage').extraAttacks<=2);});
test('Economy jobs change rewards without forcing combat stats',()=>{const s=newState(0);s.level=25;s.job='tideSurveyor';s.learned.chartedCurrents=1;s.skills=['hook','chartedCurrents'];const survey=stats(s);assert.ok(survey.dropBonus>=.03);assert.ok(survey.goldBonus>=.04);assert.ok(dropRate(s)>1.2*BALANCE.dropChance&&dropRate(s)<=BALANCE.dropChanceCap);s.job='pearlBroker';s.rebirths=1;s.learned.pearlLedger=1;s.skills=['hook','pearlLedger'];const pearls=stats(s).rebirthBonus;assert.equal(pearls,1);assert.equal(rebirthReward(s,pearls),Math.floor(s.level/10)+s.rebirths+1);s.job='salvageMerchant';s.learned.salvageContract=1;s.skills=['hook','salvageContract'];assert.ok(dungeonGoldMultiplier(s)>1);});
test('Rare fish, dungeon bosses and monster-derived skills are present',()=>{assert.ok(FISH.length>=35);assert.ok(FISH.some(f=>f.rarity==='rare'&&f.spawnWeight&&f.spawnWeight<1));assert.ok(FISH.some(f=>f.boss));assert.ok(DUNGEONS.length>=7);assert.ok(DUNGEONS.every(d=>d.bossFish));assert.ok(profile('grottoWarden').skills.includes('electricBite'));assert.ok(profile('abyssSovereign').skills.includes('tentacleBarrage'));});

test('Shop preview equals purchased item and overspending is rejected',()=>{const s=newState(0);const before=JSON.stringify(s);assert.throws(()=>act(s,{type:'buy',id:'magic'},0));assert.equal(JSON.stringify(s),before);s.gold=10000;const expected=itemStats(shopPreview(s,'magic')),cost=shopCost(s);act(s,{type:'buy',id:'magic'},0);assert.deepEqual(itemStats(s.inventory[0]),expected);assert.equal(s.gold,10000-cost);assert.ok(expected.magic>expected.attack);const id=s.inventory[0].id;act(s,{type:'equip',id},0);assert.equal(s.equipment.rod.id,id);});
test('Appraisal probability boundaries and full bag rejection',()=>{for(const [roll,rarity] of [[0,1],[.549,1],[.55,2],[.879,2],[.88,3],[.969,3],[.97,4],[.994,4],[.995,5],[.998,5],[.999,6]]){const s=newState(0);s.gold=10000;const cost=gambleCost(s);act(s,{type:'gamble',id:'physical'},0,()=>roll);assert.equal(s.inventory[0].rarity,rarity);assert.equal(s.inventory[0].affixes.length,rarity,'options = rarity');assert.equal(s.gold,10000-cost);}const s=newState(0);s.gold=9999;s.inventory=Array.from({length:60},(_,i)=>({...shopPreview(s,'coat'),id:String(i)}));const old=s.gold;assert.throws(()=>act(s,{type:'buy',id:'coat'},0));assert.equal(s.gold,old);});
test('Equipment enhancement changes real stats and caps at ten',()=>{const s=newState(0);s.gold=1e9;const item=s.equipment.rod;const cost=enhanceCost(item),before=itemStats(item).attack;act(s,{type:'enhance',id:item.id},0);assert.equal(s.gold,1e9-cost);assert.ok(Math.abs(itemStats(item).attack-before*1.15)<1e-8);for(let i=1;i<10;i++)act(s,{type:'enhance',id:item.id},0);const gold=s.gold;assert.throws(()=>act(s,{type:'enhance',id:item.id},0));assert.equal(s.gold,gold);});
test('Bulk sale respects exact rarity, locks and relics',()=>{const s=newState(0);s.inventory=[{...shopPreview(s,'coat'),id:'a'},{...shopPreview(s,'coat'),id:'b',locked:true},{...shopPreview(s,'coat'),id:'c',relic:'test'},{...shopPreview(s,'coat'),id:'d',rarity:2}];assert.equal(bulkItems(s,1).length,1);const gold=s.gold;act(s,{type:'sellRarity',id:'1'},0);assert.equal(s.gold,gold+15);assert.deepEqual(s.inventory.map(i=>i.id),['b','c','d']);assert.throws(()=>act(s,{type:'sell',id:'b'},0));assert.throws(()=>act(s,{type:'registerItem',id:'c'},0));});
test('Rebirth unlocks, research and relic persistence',()=>{const s=newState(0);s.pearls=100;s.level=30;assert.throws(()=>act(s,{type:'buyRelic',id:'memoryRod'},0));act(s,{type:'rebirth'},0);assert.equal(apCapacity(s),7);assert.equal(rebirthLevel(s),35);assert.equal(expMultiplier({...s,lifeBonus:null}),1.25);assert.equal(expMultiplier(s),1.875);act(s,{type:'permanent',id:'ap'},0);assert.equal(apCapacity(s),8);act(s,{type:'buyRelic',id:'memoryRod'},0);const relic=s.inventory[0];act(s,{type:'equip',id:relic.id},0);s.gold=10000;act(s,{type:'enhance',id:relic.id},0);s.permanent.starting=2;s.level=35;act(s,{type:'rebirth'},0);assert.equal(s.equipment.rod.relic,'memoryRod');assert.equal(s.equipment.rod.enhance,1);assert.equal(s.gold,1100);assert.equal(apCapacity(s),9);assert.throws(()=>act(s,{type:'buyRelic',id:'memoryRod'},0));s.level=100;s.rebirths=100;assert.equal(rebirthLevel(s),60);assert.ok(xpNeeded(60)<xpNeeded(30)*5);});
test('Rebirth skills still require their job; temple relic and research caps work',()=>{
 const s=newState(0);s.level=30;s.sp=100;s.pearls=1000;assert.throws(()=>act(s,{type:'learn',id:'soulHook'},0));s.rebirths=1;assert.throws(()=>act(s,{type:'learn',id:'soulHook'},0));
 s.attributes.str=20;s.attributes.wis=20;act(s,{type:'job',id:'rebirthFisher'},0);assert.equal(s.learned.soulHook,1);assert.equal(s.sp,100);
 s.clears.temple=1;const pearls=s.pearls;act(s,{type:'buyRelic',id:'memoryRod'},0);assert.equal(s.pearls,pearls);s.permanent.ap=12;assert.throws(()=>act(s,{type:'permanent',id:'ap'},0));assert.equal(s.pearls,pearls);
});
test('Gold and experience multipliers match actual combat payouts',()=>{const s=newState(0);s.rebirths=2;s.permanent.gold=2;s.permanent.exp=1;s.level=20;s.running=true;s.enemy={id:'minnow',name:'target',hp:1,maxHp:1,attack:0,defense:0,exp:10,gold:100,boss:false,stun:0};const gold=s.gold,exp=s.exp,mult=goldMultiplier(s);tick(s,()=>.5);assert.equal(s.gold-gold,Math.floor(100*mult));assert.equal(s.exp-exp,17);assert.ok(s.logs.some(l=>l.text.includes(`+${Math.floor(100*mult)} G`)));});
test('Tide scaling and endless depths advance only on full clear',()=>{const s=newState(0);assert.throws(()=>act(s,{type:'tide',id:'1'},0));s.rebirths=3;act(s,{type:'tide',id:'2'},0);s.running=true;tick(s,()=>.5);assert.ok(s.enemy.maxHp>50);s.level=100;s.permanent.attack=4000;s.permanent.hp=4000;act(s,{type:'dungeon',id:'abyss'},0);assert.equal(s.dungeon.depth,1);assert.throws(()=>act(s,{type:'tide',id:'1'},0));for(let i=0;i<20&&s.running;i++)tick(s,()=>.5);assert.equal(s.abyssBest,1);assert.equal(s.pearls,1);act(s,{type:'dungeon',id:'abyss'},0);assert.equal(s.dungeon.depth,2);act(s,{type:'leaveDungeon'},0);assert.equal(s.abyssBest,1);assert.equal(s.pearls,1);act(s,{type:'dungeon',id:'abyss'},0);for(let i=0;i<20&&s.running;i++)tick(s,()=>.5);assert.equal(s.abyssBest,2);assert.equal(s.pearls,2);});
test('Accuracy and evasion use the displayed formula',()=>{assert.ok(Math.abs(hitChance({accuracy:.94},{evasion:.14})-.8)<1e-9);assert.ok(Math.abs(hitChance({accuracy:.94},{evasion:.24})-.7)<1e-9);assert.equal(hitChance({accuracy:2},{evasion:0}),.995);assert.equal(hitChance({accuracy:.1},{evasion:.8}),.01);});
test('Guild keeps name, join, honor donations and records but gives no growth; removed actions are rejected',()=>{const s=newState(0);assert.throws(()=>act(s,{type:'guildJoin',value:'심해개척단'},0));s.gold=10000;s.level=20;act(s,{type:'guildJoin',value:'파도연합'},0);assert.equal(s.gold,9000);act(s,{type:'guildRename',value:'푸른파도'},0);assert.equal(s.guild.name,'푸른파도');assert.equal(s.gold,8500);const before=JSON.stringify(stats(s)),drop=dropRate(s),gm=goldMultiplier(s);act(s,{type:'guildDonate',id:'1000'},0);assert.equal(s.guild.contribution,1000);assert.equal(JSON.stringify(stats(s)),before);assert.equal(dropRate(s),drop);assert.equal(goldMultiplier(s),gm);s.guild.research={might:10,bastion:10,treasury:10,scouting:10};assert.equal(JSON.stringify(stats(s)),before,'old research records grant nothing');for(const type of ['guildResearch','guildClaim','guildRaid'])assert.throws(()=>act(s,{type,id:'might'},0),/삭제된 길드 기능/);const medals=s.guild.medals;act(s,{type:'guildDonate',id:'5000'},0);assert.equal(s.guild.medals,medals,'no medals from donations');assert.equal(snapshot(s).guild,'푸른파도');s.level=30;s.gold=10000;const saved=JSON.stringify(s.guild);act(s,{type:'rebirth'},0);assert.equal(JSON.stringify(s.guild),saved);});
